### ISSUE TITLE
full Kubernetes application using ClusterIP

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#19]
---

### **📌 What Are We Doing?**  
We will deploy a **backend (Flask API) and a frontend (Nginx)** in Kubernetes, using **ClusterIP** to connect them internally.

---

### **📌 Steps to Deploy**  

✅ **Step 1: Create Backend (Flask API)**  
- Write a `Dockerfile` for Flask.  
- Build & push the image to Docker Hub.  

```sh
docker build -t your-dockerhub-username/backend-app .
docker push your-dockerhub-username/backend-app
```

✅ **Step 2: Deploy Backend in Kubernetes**  
- Create **Deployment** (`backend-deployment.yaml`).  
- Create a **ClusterIP Service** (`backend-service.yaml`).  

```yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 5000
  type: ClusterIP
```
🔹 **Frontend will access backend using `http://backend-service:8080`.**  

✅ **Step 3: Deploy Frontend (Nginx)**  
- Create **Nginx Deployment** (`frontend-deployment.yaml`).  
- Use **ConfigMap** to configure Nginx (`nginx-configmap.yaml`).  
- Create **NodePort Service** (`frontend-service.yaml`).  

```yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
```

✅ **Step 4: Apply Everything**
```sh
kubectl apply -f backend-deployment.yaml
kubectl apply -f backend-service.yaml
kubectl apply -f nginx-configmap.yaml
kubectl apply -f frontend-deployment.yaml
kubectl apply -f frontend-service.yaml
```

✅ **Step 5: Access the App**  
- Get the NodePort using:  
  ```sh
  kubectl get svc frontend-service
  ```
- Open in browser:  
  ```
  http://<your-node-ip>:<NodePort>
  ```

---

### **📌 What’s Happening?**
🚀 **Frontend talks to backend via ClusterIP** (only inside Kubernetes).  
🌍 **Frontend is exposed using NodePort** (accessible from outside).  

---

### **📌 What’s Next?**  
🔹 Want to use **LoadBalancer** instead of NodePort?  
🔹 Need help with **AWS/GCP deployment**?  

Let me know! 🚀😊
