### ISSUE TITLE
Deploy Kubernetes using kubectl apply on Akamai Linode Kubernetes Engine (LKE)

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#25]
You can deploy Kubernetes using kubectl apply on Akamai Linode Kubernetes Engine (LKE). Here’s how to do it step by step.

🛠️ Setting Up Kubernetes on Akamai Linode (LKE)
1. Create a Kubernetes Cluster on Linode
Log in to Akamai Linode Cloud Manager.
Click Kubernetes > Create Cluster.
Choose:
Region: Select a nearby location.
Kubernetes Version: Latest stable version.
Node Pool: Choose at least 1 node.
Click Create Cluster and wait for deployment.
2. Install & Configure kubectl and linode-cli on Your Local Machine
Install kubectl (If Not Installed)
sh
Copy
Edit
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
chmod +x kubectl
sudo mv kubectl /usr/local/bin/
kubectl version --client
Install Linode CLI
sh
Copy
Edit
curl -s https://cloud.linode.com/scripts/linode-cli/install.sh | sudo bash
Login and authenticate:

sh
Copy
Edit
linode-cli configure
Download Cluster Config
sh
Copy
Edit
linode-cli lke kubeconfig-view <cluster-id> --json | jq -r '.[] | .kubeconfig' > kubeconfig.yaml
export KUBECONFIG=kubeconfig.yaml
To verify:

sh
Copy
Edit
kubectl cluster-info
3. Deploy an Nginx Pod Using kubectl apply
Step 1: Create a YAML File (nginx.yaml)
yaml
Copy
Edit
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx:1.19
Step 2: Apply the Configuration
sh
Copy
Edit
kubectl apply -f nginx.yaml
Step 3: Verify Deployment
sh
Copy
Edit
kubectl get pods
kubectl describe pod myapp-pod
Step 4: Expose the Pod (Optional)
sh
Copy
Edit
kubectl expose pod myapp-pod --type=LoadBalancer --port=80 --target-port=80
Step 5: Get the External IP
sh
Copy
Edit
kubectl get services
✅ Why Use Akamai Linode for Kubernetes?
Simple and Cost-Effective: Cheaper than AWS/GCP.
Managed Kubernetes: Linode handles cluster setup.
Scalable and Secure: Integrates with Linode’s networking and security.
Would you like me to help with setting up a full Kubernetes workload or a database connection on Linode? 🚀

You said:
yes
ChatGPT said:
🚀 Setting Up a Full Kubernetes Workload on Akamai Linode (LKE)
This guide will help you deploy a scalable web application with a database on Akamai Linode Kubernetes Engine (LKE). We'll use Nginx for the frontend and MongoDB as the database.

1️⃣ Setup Linode Kubernetes Cluster
If you haven't already created a Kubernetes cluster on Linode, follow these steps:

Log in to Akamai Linode Cloud Manager.
Navigate to Kubernetes > Create Cluster.
Choose:
Region: Select the closest region.
Kubernetes Version: Use the latest stable version.
Node Pool: Choose at least 2 nodes (recommended for HA).
Click Create Cluster and wait for provisioning.
2️⃣ Install & Configure kubectl and linode-cli
Install kubectl (If Not Installed)
sh
Copy
Edit
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
chmod +x kubectl
sudo mv kubectl /usr/local/bin/
kubectl version --client
Install Linode CLI
sh
Copy
Edit
curl -s https://cloud.linode.com/scripts/linode-cli/install.sh | sudo bash
Log in and configure:

sh
Copy
Edit
linode-cli configure
Download Cluster Configuration
sh
Copy
Edit
linode-cli lke kubeconfig-view <cluster-id> --json | jq -r '.[] | .kubeconfig' > kubeconfig.yaml
export KUBECONFIG=kubeconfig.yaml
Test the connection:

sh
Copy
Edit
kubectl cluster-info
3️⃣ Deploy an Nginx Web App
Create a Deployment (nginx-deployment.yaml)
yaml
Copy
Edit
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
Apply the Deployment
sh
Copy
Edit
kubectl apply -f nginx-deployment.yaml
Expose the Deployment (nginx-service.yaml)
yaml
Copy
Edit
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
Apply the Service
sh
Copy
Edit
kubectl apply -f nginx-service.yaml
Get the External IP
sh
Copy
Edit
kubectl get services
Once the EXTERNAL-IP is assigned, you can visit it in your browser.

4️⃣ Deploy MongoDB as a Database
Create a MongoDB Deployment (mongodb-deployment.yaml)
yaml
Copy
Edit
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
Apply the MongoDB Deployment
sh
Copy
Edit
kubectl apply -f mongodb-deployment.yaml
Expose MongoDB with a Service (mongodb-service.yaml)
yaml
Copy
Edit
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
Apply the Service
sh
Copy
Edit
kubectl apply -f mongodb-service.yaml
5️⃣ Verify and Test the Deployment
Check All Pods
sh
Copy
Edit
kubectl get pods
Output:

sql
Copy
Edit
NAME                               READY   STATUS    RESTARTS   AGE
nginx-deployment-xxxxx             1/1     Running   0          30s
nginx-deployment-yyyyy             1/1     Running   0          30s
mongodb-xxxxx                      1/1     Running   0          30s
Check Services
sh
Copy
Edit
kubectl get services
Output:

pgsql
Copy
Edit
NAME              TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)        
nginx-service    LoadBalancer   10.128.100.200   <pending>       80:31927/TCP   
mongodb-service  ClusterIP      None             <none>          27017/TCP  
Test MongoDB Connection
sh
Copy
Edit
kubectl exec -it <mongodb-pod-name> -- mongo --host mongodb-service --username admin --password password
Once inside MongoDB shell:

sh
Copy
Edit
show dbs;
✅ Summary
✔ We deployed Nginx as a frontend.
✔ We deployed MongoDB as a database.
✔ We exposed Nginx using a LoadBalancer for public access.
✔ We exposed MongoDB using a ClusterIP for internal app access.

🚀 Next Steps
Deploy an application (e.g., Node.js, Python, PHP) to use MongoDB.
Set up Ingress Controller for better routing.
Enable persistent storage for MongoDB.
Integrate CI/CD using GitHub Actions or Jenkins.
Would you like help with adding a backend API or setting up CI/CD? 🔥🚀

Awesome! Let's break this into **two phases**:  

### **📌 Phase 1: Adding a Backend API**
We'll deploy a **Node.js API** that connects to **MongoDB** and serves data to the frontend.  

### **📌 Phase 2: Setting up CI/CD**
We'll use **GitHub Actions** to automate the deployment of our application to **Linode Kubernetes Engine (LKE)**.  

---

# **🚀 Phase 1: Deploying a Node.js Backend API**
## **Step 1: Create a Simple Node.js API**
We’ll create a basic **Express.js API** that connects to MongoDB.

### **1️⃣ Create the Node.js Application**
```sh
mkdir backend-api && cd backend-api
npm init -y
npm install express mongoose cors dotenv
```

### **2️⃣ Create `server.js`**
```javascript
require("dotenv").config();
const express = require("express");
const mongoose = require("mongoose");

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware
app.use(express.json());

// Connect to MongoDB
mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const db = mongoose.connection;
db.once("open", () => console.log("Connected to MongoDB"));

// Sample Route
app.get("/", (req, res) => {
  res.send("Hello from Node.js API!");
});

// Start Server
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
```

### **3️⃣ Create `.env`**
```sh
MONGO_URI=mongodb://admin:password@mongodb-service:27017
PORT=5000
```

---

### **1️⃣ Create a `Dockerfile`**
```dockerfile
FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
CMD ["node", "server.js"]
EXPOSE 5000
```

### **2️⃣ Create a `docker-compose.yml` (Optional for Local Testing)**
```yaml
version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb-service:27017
```

---

### **1️⃣ Create `backend-deployment.yaml`**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub-username/backend-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://admin:password@mongodb-service:27017"
```

### **2️⃣ Create `backend-service.yaml`**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
```

### **3️⃣ Apply the Deployment**
```sh
kubectl apply -f backend-deployment.yaml
kubectl apply -f backend-service.yaml
```

---

## **✅ Verify the Backend**
```sh
kubectl get pods
kubectl get services
```
To test the API:
```sh
kubectl port-forward svc/backend-service 5000:5000
```
Then visit: **`http://localhost:5000/`** in your browser.

---

# **🚀 Phase 2: Setting Up CI/CD with GitHub Actions**
## **Step 1: Create `.github/workflows/deploy.yaml`**
```yaml
name: Deploy to Linode Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/backend-api:latest .
          docker push your-dockerhub-username/backend-api:latest

      - name: Set Up Kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f backend-deployment.yaml
          kubectl apply -f backend-service.yaml
```

---

## **✅ Summary**
✔ **Added a Node.js API that connects to MongoDB.**  
✔ **Dockerized the application.**  
✔ **Deployed it to Linode Kubernetes.**  
✔ **Set up a GitHub Actions CI/CD pipeline.**  

Would you like help with **frontend deployment** or **monitoring/logging setup**? 🚀

--------------------------------------------------------------------------------------------

**frontend deployment** or **monitoring/logging setup**? 

--------------------------------------------------------------------------------------------

Awesome! Let's break it down into **two phases**:  

---

## **📌 Phase 1: Deploying the Frontend (React.js) to Linode Kubernetes**  
We'll deploy a **React.js frontend** that connects to the backend API.

## **📌 Phase 2: Setting Up Monitoring & Logging**  
We'll use **Prometheus, Grafana, and Loki** to monitor and log our Kubernetes cluster.

---

# **🚀 Phase 1: Deploying the React Frontend**  
## **Step 1: Create a React App**  
If you haven’t already created a frontend, generate a new React app:  
```sh
npx create-react-app frontend
cd frontend
```
  
### **1️⃣ Update `src/App.js` to Call the Backend API**  
Modify `App.js` to fetch data from the backend:
```javascript
import { useEffect, useState } from "react";

function App() {
  const [message, setMessage] = useState("");

  useEffect(() => {
    fetch("http://backend-service:5000/")
      .then((res) => res.text())
      .then((data) => setMessage(data));
  }, []);

  return (
    <div>
      <h1>React Frontend</h1>
      <p>Backend Message: {message}</p>
    </div>
  );
}

export default App;
```

---

### **1️⃣ Create a `Dockerfile`**
```dockerfile
FROM node:18 as build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:latest
COPY --from=build /app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 80
```

### **2️⃣ Build and Push the Docker Image**
```sh
docker build -t your-dockerhub-username/frontend:latest .
docker push your-dockerhub-username/frontend:latest
```

---

### **1️⃣ Create `frontend-deployment.yaml`**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-dockerhub-username/frontend:latest
          ports:
            - containerPort: 80
```

### **2️⃣ Create `frontend-service.yaml`**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
```

---

## **Step 4: Apply the Deployment**
```sh
kubectl apply -f frontend-deployment.yaml
kubectl apply -f frontend-service.yaml
```

### **✅ Access the Frontend**
Get the external IP of the frontend:
```sh
kubectl get services
```
Visit **`http://<EXTERNAL_IP>`** in your browser.

---

# **🚀 Phase 2: Monitoring & Logging with Prometheus, Grafana & Loki**
### **1️⃣ Create `prometheus-deployment.yaml`**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
```

### **2️⃣ Create `prometheus-service.yaml`**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
```
---
### **1️⃣ Create `grafana-deployment.yaml`**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
```

### **2️⃣ Create `grafana-service.yaml`**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
```

### **✅ Access Grafana**
```sh
kubectl get services
```
Visit **`http://<EXTERNAL_IP>:3000`**, login with **admin/admin**, and add Prometheus as a data source.

---

### **1️⃣ Create `loki-deployment.yaml`**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki
          ports:
            - containerPort: 3100
```

### **2️⃣ Create `loki-service.yaml`**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: loki-service
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: ClusterIP
```

---

# **✅ Summary**
✔ **Deployed a React frontend with a backend API.**  
✔ **Set up Prometheus for monitoring.**  
✔ **Configured Grafana for dashboards.**  
✔ **Deployed Loki for logging.**  

---

**💡 Next Steps:**  
- Would you like to **secure the deployment** using **SSL (Let's Encrypt, Cert-Manager)?**  
- Do you need **alerts using Prometheus & Grafana?** 🚀

--------------------------------------------------------------------------------------------
Setting Up Alerting in Grafana Using Prometheus
--------------------------------------------------------------------------------------------

Setting Up Alerting in Grafana Using Prometheus
We'll configure Grafana Alerts using Prometheus as the data source and set up email/slack notifications.

📌 Step 1: Enable Alerting in Grafana
1️⃣ Add Prometheus as a Data Source
Open Grafana (http://<EXTERNAL_IP>:3000)
Go to Settings → Data Sources
Click Add data source
Select Prometheus and enter:
URL: http://prometheus-service:9090
Click Save & Test
📌 Step 2: Configure Prometheus Alert Rules
1️⃣ Create alert-rules.yaml
yaml
Copy
Edit
groups:
  - name: example-alerts
    rules:
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[1m]) > 0.7
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High CPU Usage detected"
          description: "Container CPU usage is above 70% for more than 2 minutes"
2️⃣ Apply the Alert Rules
sh
Copy
Edit
kubectl apply -f alert-rules.yaml
📌 Step 3: Deploy Alertmanager
1️⃣ Create alertmanager-config.yaml
yaml
Copy
Edit
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      receiver: 'email-alert'
      routes:
        - match:
            severity: critical
          receiver: 'email-alert'

    receivers:
      - name: 'email-alert'
        email_configs:
          - to: 'your-email@example.com'
            from: 'alertmanager@example.com'
            smarthost: 'smtp.gmail.com:587'
            auth_username: 'your-email@example.com'
            auth_password: 'your-email-password'
2️⃣ Deploy Alertmanager
yaml
Copy
Edit
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
3️⃣ Deploy Alertmanager Service
yaml
Copy
Edit
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
spec:
  selector:
    app: alertmanager
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
  type: ClusterIP
sh
Copy
Edit
kubectl apply -f alertmanager-config.yaml
kubectl apply -f alertmanager-deployment.yaml
kubectl apply -f alertmanager-service.yaml
📌 Step 4: Connect Alertmanager to Prometheus
Modify prometheus-deployment.yaml
yaml
Copy
Edit
containers:
  - name: prometheus
    image: prom/prometheus
    args:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--alertmanager.url=http://alertmanager-service:9093"
sh
Copy
Edit
kubectl apply -f prometheus-deployment.yaml
📌 Step 5: Configure Grafana Alerting
Go to Grafana → Alerting → Contact Points
Click New Contact Point → Choose Email / Slack / Webhook
Configure it (e.g., add your Slack webhook URL for Slack alerts)
Save it and create an Alert Rule
✅ Summary
✔ Configured Prometheus alert rules 📊
✔ Deployed Alertmanager for alert processing 🔔
✔ Integrated email/Slack alerts 💬
✔ Connected Grafana for alert visualization 🚀

Would you like to add webhook alerts or custom alert thresholds? 😊

--------------------------------------------------------------------------------------------
Adding Custom Alert Thresholds in Prometheus & Grafana
--------------------------------------------------------------------------------------------

Adding Custom Alert Thresholds in Prometheus & Grafana
We’ll configure custom alert thresholds for CPU, Memory, and Disk usage in Prometheus and Grafana.

📌 Step 1: Define Custom Alert Rules in Prometheus
Create a custom alert rule file (custom-alerts.yaml) with specific thresholds.

yaml
Copy
Edit
groups:
  - name: custom-alerts
    rules:
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[1m]) > 0.8
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU Usage"
          description: "CPU usage has exceeded 80% for 1 minute."

      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.9
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Memory Usage"
          description: "Memory usage is above 90% for 2 minutes."

      - alert: LowDiskSpace
        expr: node_filesystem_free_bytes / node_filesystem_size_bytes < 0.2
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low Disk Space"
          description: "Available disk space is below 20%."
🚀 Apply the Custom Alert Rules
sh
Copy
Edit
kubectl apply -f custom-alerts.yaml
📌 Step 2: Update Prometheus Configuration
Modify prometheus.yml to load custom alert rules.

yaml
Copy
Edit
rule_files:
  - "custom-alerts.yaml"
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager-service:9093"
sh
Copy
Edit
kubectl apply -f prometheus-config.yaml
📌 Step 3: Create Custom Alerts in Grafana
1️⃣ Create a New Alert in Grafana
Go to Grafana → Alerting → Alert Rules
Click "Create Alert Rule"
Choose a Metric (e.g., container_cpu_usage_seconds_total)
Set a Condition:
Expression: rate(container_cpu_usage_seconds_total[1m])
Threshold: > 0.8
Duration: 1m
Add Contact Point (Slack, Email, Webhook)
Save Alert Rule
📌 Step 4: Verify Alerts
Check alerts in Grafana → Alerting → Alert Rules
Run a high CPU load test:
sh
Copy
Edit
kubectl run stress-test --image=alpine -- sh -c "apk add --no-cache stress && stress --cpu 2 --timeout 60s"
Check alerts in Prometheus (/alerts endpoint)
sh
Copy
Edit
kubectl port-forward svc/prometheus-service 9090
Open http://localhost:9090/alerts
✅ Summary
✔ Created custom alert rules for CPU, Memory, and Disk 📊
✔ Configured Prometheus & Alertmanager thresholds 🔥
✔ Added Grafana alerts for visualization & notifications 🚀

Would you like to add webhook alerts or set up Slack notifications? 😊

--------------------------------------------------------------------------------------------
### **🚀 Setting Up Slack Notifications for Grafana Alerts**  
--------------------------------------------------------------------------------------------

We’ll configure **Slack notifications** using **Alertmanager** and **Grafana Alerting**.

---

## **📌 Step 1: Create a Slack Webhook**
1. Open **Slack** and go to **Apps → Incoming Webhooks**  
2. Click **Create New Webhook**  
3. Choose a channel (e.g., `#alerts`)  
4. Copy the **Webhook URL** (e.g., `https://hooks.slack.com/services/XXX/YYY/ZZZ`)  

---

## **📌 Step 2: Configure Alertmanager for Slack Alerts**
Modify the **Alertmanager ConfigMap** to add Slack as a receiver.  

### **1️⃣ Edit `alertmanager-config.yaml`**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: slack-alerts
      group_by: ['alertname']
      repeat_interval: 5m
      routes:
        - match:
            severity: critical
          receiver: slack-alerts

    receivers:
      - name: 'slack-alerts'
        slack_configs:
          - send_resolved: true
            channel: '#alerts'
            api_url: 'https://hooks.slack.com/services/XXX/YYY/ZZZ'
            title: "🔥 Alert: {{ .CommonLabels.alertname }}"
            text: "🚨 *Alert:* {{ .CommonLabels.alertname }}\n📍 *Instance:* {{ .CommonLabels.instance }}\n🕒 *Time:* {{ .StartsAt }}"
```

---

### **2️⃣ Apply the Configuration**
```sh
kubectl apply -f alertmanager-config.yaml
kubectl delete pod -l app=alertmanager  # Restart Alertmanager
```

---

## **📌 Step 3: Configure Grafana for Slack Alerts**
1. **Go to Grafana → Alerting → Contact Points**  
2. Click **New Contact Point**  
3. Select **Slack**  
4. **Enter Webhook URL** (`https://hooks.slack.com/services/XXX/YYY/ZZZ`)  
5. Choose a **Channel** (e.g., `#alerts`)  
6. **Test & Save**  

---

## **📌 Step 4: Verify Slack Alerts**
1. Create a **test alert in Grafana** (CPU above 10%)  
2. Check **Slack (#alerts)** for notifications  
3. Trigger a **CPU spike test**:
```sh
kubectl run stress-test --image=alpine -- sh -c "apk add --no-cache stress && stress --cpu 2 --timeout 60s"
```

---

## **✅ Summary**
✔ **Configured Alertmanager for Slack notifications**  
✔ **Set up Slack Webhook in Grafana**  
✔ **Tested Slack Alerts with Prometheus & Grafana** 🚀  

Would you like to **add Discord or webhook alerts** next? 😊
