### ISSUE TITLE
Project: Building a Web Application with Nginx and MySQL Using Docker Volumes

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#3]
In this project, we will:

1. Set up an Nginx container to serve a simple web application.
2. Set up a MySQL database container to store user data.
3. Use Docker volumes to persist data in both containers.

---

### 1. **Setup the Project Structure**

Let's first define a simple structure for our project. 

**Directory Structure:**
```
/my-docker-project
  |-- /html
  |    |-- index.html
  |-- /db-data (this is where MySQL data will persist)
  |-- docker-compose.yml
```

### 2. **Create the Web Application (Nginx)**

We will create a simple `index.html` file to serve as the web application.

**Step 1: Create `index.html`**

In the `/html` folder, create a simple `index.html` file:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Docker Web App</title>
</head>
<body>
  <h1>Welcome to My Dockerized Web App!</h1>
  <p>This is a simple web page served by Nginx.</p>
</body>
</html>
```

### 3. **Create a Docker Compose File**

We will use Docker Compose to manage both containers (Nginx and MySQL) and volumes.

**Step 2: Create `docker-compose.yml`**

In the root of the project folder (`/my-docker-project`), create a file called `docker-compose.yml`:

```yaml
version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./html:/usr/share/nginx/html  # Mount the HTML folder to Nginx's HTML directory
      - nginx-logs:/var/log/nginx     # Volume for Nginx logs
    ports:
      - "80:80"
    networks:
      - webnet

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password for MySQL
      MYSQL_DATABASE: webappdb           # Create a database named "webappdb"
    volumes:
      - mysql-data:/var/lib/mysql  # Mount volume for MySQL data persistence
    networks:
      - webnet

volumes:
  nginx-logs: {}
  mysql-data: {}

networks:
  webnet: {}
```

### Explanation of the `docker-compose.yml` File:

- **Web Service (Nginx)**:
  - Mounts the `/html` directory from your local machine to the Nginx container’s `/usr/share/nginx/html`, where the web content is served.
  - Mounts a volume for Nginx logs (`nginx-logs`) so logs are saved even after the container is stopped.
  - Maps port `80` on your local machine to port `80` in the container (so you can access the app on your browser at `http://localhost`).

- **DB Service (MySQL)**:
  - Sets up a MySQL database with a root password and creates a database called `webappdb`.
  - Mounts a volume (`mysql-data`) to store MySQL’s data persistently.

- **Volumes**:
  - `nginx-logs`: Stores the logs for Nginx.
  - `mysql-data`: Stores the MySQL database files.
  
- **Networks**:
  - Both containers (`web` and `db`) are connected to a common network (`webnet`), allowing them to communicate with each other.

---

### 4. **Running the Project**

**Step 3: Start the Project Using Docker Compose**

In the terminal, navigate to the project folder and run the following command to start the containers:

```bash
docker-compose up -d
```

- This will pull the necessary Docker images (Nginx, MySQL), create the containers, and start the application in detached mode (`-d`).

**Step 4: Verify Everything Is Running**

You can verify that the containers are running by checking the status:

```bash
docker ps
```

You should see the following two containers running:
1. `nginx-server` (Web app container).
2. `mysql-db` (MySQL database container).

**Step 5: Access the Web Application**

Open a web browser and visit `http://localhost`. You should see the "Welcome to My Dockerized Web App!" page.

---

### 5. **Check Volume Persistence**

Now, let's test the persistence of the volumes.

1. **Test Nginx Logs Persistence**:
   - You can check the Nginx access logs even after restarting the container, as they are stored in the `nginx-logs` volume.

2. **Test MySQL Data Persistence**:
   - You can test data persistence by interacting with the MySQL database.

**Step 1: Access MySQL Container**

```bash
docker exec -it mysql-db mysql -uroot -prootpassword
```

This will log you into the MySQL command line interface (CLI).

**Step 2: Create a Table and Insert Data**

```sql
USE webappdb;
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100));
INSERT INTO users (name) VALUES ('Alice'), ('Bob');
```

**Step 3: Check if Data is Saved**

Exit the MySQL CLI and stop the MySQL container:

```bash
docker stop mysql-db
```

**Step 4: Restart the Containers**

Now, start the containers again:

```bash
docker-compose up -d
```

**Step 5: Verify Data Persistence**

Access the MySQL container again:

```bash
docker exec -it mysql-db mysql -uroot -prootpassword
```

Run the following query to check if the data is still there:

```sql
USE webappdb;
SELECT * FROM users;
```

You should see the data you inserted earlier (`Alice` and `Bob`), proving that the MySQL data is persistent.

---

### 6. **Clean Up**

After you’re done with the project, you can remove the containers and volumes:

```bash
docker-compose down -v
```

The `-v` flag will remove the volumes as well, cleaning up everything.

---

### Conclusion

In this large project, we:
1. **Created a multi-container application** with Nginx (for serving a web page) and MySQL (for database storage).
2. **Used Docker volumes** to persist data for both Nginx logs and MySQL database data.
3. **Tested volume persistence** by restarting containers and verifying that data was not lost.

This is a good example of how Docker volumes help in storing data outside containers, ensuring that the data survives even if containers are stopped or removed.
