### ISSUE TITLE
Kubernetes project where we implement multiple schedulers

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#37]
Let's create a **small Kubernetes project** where we implement **multiple schedulers** by deploying a **custom scheduler** alongside the default `kube-scheduler`. This project will:  

✅ **Deploy a custom scheduler** in Kubernetes  
✅ **Schedule specific Pods** using the custom scheduler  
✅ **Verify how multiple schedulers work**  

---

# **Project: Running Multiple Schedulers in Kubernetes** 🚀  

## **Step 1: Set Up a Kubernetes Cluster**  
Make sure you have a Kubernetes cluster running. You can use:  
🔹 **Minikube** (for local testing)  
🔹 **Kind (Kubernetes-in-Docker)**  
🔹 **Cloud-based Kubernetes (EKS, AKS, GKE, etc.)**  

Start Minikube (if using local setup):  
```sh
minikube start
```

Verify the cluster is running:  
```sh
kubectl get nodes
```

---

## **Step 2: Deploy the Default Kubernetes Scheduler (Optional)**
Kubernetes already has `kube-scheduler` running, but you can check it with:  
```sh
kubectl get pods -n kube-system | grep scheduler
```
You'll see something like:  
```
kube-scheduler-minikube   1/1   Running   0   5m
```

---

## **Step 3: Create a Custom Scheduler** 🏗️  
We will create a simple custom scheduler in **Go** that schedules Pods to the least loaded node.

### **3.1 Write the Go Code for Custom Scheduler**
Create a new file **`custom-scheduler.go`**:
```go
package main

import (
    "context"
    "fmt"
    "log"
    "time"

    v1 "k8s.io/api/core/v1"
    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
    "k8s.io/client-go/kubernetes"
    "k8s.io/client-go/rest"
)

func main() {
    config, err := rest.InClusterConfig()
    if err != nil {
        log.Fatal(err)
    }

    clientset, err := kubernetes.NewForConfig(config)
    if err != nil {
        log.Fatal(err)
    }

    for {
        pods, err := clientset.CoreV1().Pods("").List(context.TODO(), metav1.ListOptions{})
        if err != nil {
            log.Println("Error fetching pods:", err)
            continue
        }

        for _, pod := range pods.Items {
            if pod.Spec.SchedulerName == "custom-scheduler" && pod.Status.Phase == v1.PodPending {
                nodes, err := clientset.CoreV1().Nodes().List(context.TODO(), metav1.ListOptions{})
                if err != nil {
                    log.Println("Error fetching nodes:", err)
                    continue
                }

                if len(nodes.Items) == 0 {
                    log.Println("No nodes available for scheduling")
                    continue
                }

                chosenNode := nodes.Items[0].Name
                fmt.Println("Assigning Pod", pod.Name, "to Node", chosenNode)

                binding := &v1.Binding{
                    ObjectMeta: metav1.ObjectMeta{Name: pod.Name},
                    Target: v1.ObjectReference{
                        Kind: "Node",
                        Name: chosenNode,
                    },
                }

                err = clientset.CoreV1().Pods(pod.Namespace).Bind(context.TODO(), binding, metav1.CreateOptions{})
                if err != nil {
                    log.Println("Failed to bind pod:", err)
                } else {
                    log.Println("Pod", pod.Name, "successfully scheduled on", chosenNode)
                }
            }
        }

        time.Sleep(5 * time.Second)
    }
}
```

### **3.2 Build and Package the Custom Scheduler**
Build a Docker image for our scheduler:  
```sh
docker build -t custom-scheduler:v1 .
```

Push it to Docker Hub (replace `your-docker-id`):  
```sh
docker tag custom-scheduler:v1 your-docker-id/custom-scheduler:v1
docker push your-docker-id/custom-scheduler:v1
```

---

### **4.1 Create a Deployment for the Custom Scheduler**
Create a new file **`custom-scheduler-deployment.yaml`**:  
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: custom-scheduler
  template:
    metadata:
      labels:
        component: custom-scheduler
    spec:
      containers:
        - name: custom-scheduler
          image: your-docker-id/custom-scheduler:v1
```

Apply it to the cluster:  
```sh
kubectl apply -f custom-scheduler-deployment.yaml
```

Check if it’s running:  
```sh
kubectl get pods -n kube-system | grep custom-scheduler
```

---

## **Step 5: Schedule a Pod with the Custom Scheduler** 🎯  
Create a **test Pod** that will use our custom scheduler.

### **5.1 Create a Test Pod**
Create a new file **`test-pod.yaml`**:  
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-custom-scheduled-pod
spec:
  schedulerName: custom-scheduler  # Use our custom scheduler
  containers:
    - name: nginx-container
      image: nginx
```

Apply it to the cluster:  
```sh
kubectl apply -f test-pod.yaml
```

Check if the Pod is scheduled:  
```sh
kubectl get pods
```

---

### **6.1 Check Pod Scheduling**  
Run the command to check **where the Pod is scheduled**:  
```sh
kubectl get pods -o wide
```
You should see your Pod scheduled on a node by `custom-scheduler`.  

### **6.2 Check Scheduler Logs**  
If there are issues, check the logs of our custom scheduler:  
```sh
kubectl logs -n kube-system -l component=custom-scheduler
```

### **6.3 Check Default Scheduler is Still Working**
Deploy another Pod **without specifying `schedulerName`**:  
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: default-scheduled-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
```

Apply it:  
```sh
kubectl apply -f default-pod.yaml
```

Check where this Pod is scheduled:  
```sh
kubectl get pods -o wide
```
It should be scheduled by `kube-scheduler` (default scheduler).  

---

# **Project Summary 🚀**  
✔️ We **deployed a custom scheduler** alongside Kubernetes’ default scheduler.  
✔️ We **scheduled specific Pods** using our custom scheduler.  
✔️ We **verified that multiple schedulers are working correctly**.  

---

## **Next Steps 🔥**  
🎯 **Enhance the custom scheduler** – Add more intelligent scheduling logic (e.g., scheduling based on CPU/memory).  
🎯 **Deploy on a real cloud Kubernetes cluster** (EKS, AKS, or GKE).  
🎯 **Monitor scheduler performance** with Prometheus & Grafana.  

Would you like a **Python version** of the custom scheduler? Let me know! 🚀
