### ISSUE TITLE
Kubernetes Scheduler Profile

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#38]
---

# **📌 Kubernetes Scheduler Profile Explained (Step-by-Step)**
The **Kubernetes scheduler** is responsible for deciding **which node** a Pod should be placed on. But what if you **want to customize** how the scheduling works? 🤔  

That’s where **Scheduler Profiles** come in! 🎯 They allow us to define **custom scheduling rules** to control how Pods are assigned to nodes.

---

## **💡 How Does the Scheduler Work?**
When a Pod is created, the scheduler follows these steps:  

1️⃣ **Scheduling Queue** → The Pod enters a queue and gets sorted based on priority.  
2️⃣ **Filtering** → The scheduler **removes** nodes that don’t meet the Pod’s requirements.  
3️⃣ **Scoring** → The scheduler gives **scores** to the remaining nodes based on factors like CPU, memory, and affinity.  
4️⃣ **Binding** → The scheduler assigns the Pod to the highest-scored node.  

### 🔥 **Now, here’s the cool part**:  
With **scheduler profiles**, you can **customize** these steps! 🚀 You can enable or disable certain **plugins** (predefined logic that helps in scheduling).  

---

![Image](https://github.com/user-attachments/assets/2723257d-6884-4aed-8a4f-a5f952ee66a7)

## **🛠️ What is in the Image?**
Your image shows the **Kubernetes Scheduling Framework**. It has:  

🔴 **Extension Points (Pink Boxes)** → These are different **stages** of scheduling.  
🔵 **Plugins (Blue Boxes)** → These are **Scheduling Plugins** that help in making scheduling decisions.  

Now, let’s go **step by step** and explain each **extension point** and its **plugins**.  

---

# **📌 1. Scheduling Queue (Sorting Pods)**
### 🔴 `queueSort` (Extension Point)  
📌 **What it does?** → Sorts pending Pods based on priority.  

🔵 **Plugin: PrioritySort**  
✔️ Sorts Pods so that high-priority ones are scheduled first.  

🔹 Example: If you have two Pods, one with **high priority** and another with **low priority**, this plugin ensures the high-priority Pod gets scheduled first! 🚀  

---

# **📌 2. Filtering (Removing Nodes that Don’t Match)**
### 🔴 `preFilter` (Extension Point)  
📌 **What it does?** → Runs **before filtering** to check if the Pod has enough resources.  

🔵 **Plugin: NodeResourcesFit**  
✔️ Ensures the node has enough CPU & memory for the Pod.  

🔴 `filter` (Extension Point)  
📌 **What it does?** → Removes nodes that **don’t meet** Pod requirements.  

🔵 **Plugins:**  
✔️ `NodeName` → Only allows Pods on a specific node (if defined).  
✔️ `NodeUnschedulable` → Ignores nodes marked as **unschedulable**.  
✔️ `NodePorts` → Ensures that the node has the required network ports.  
✔️ `TaintToleration` → Ensures Pods tolerate node **taints** (like a "Do Not Disturb" sign on a node).  
✔️ `NodeAffinity` → Checks if a Pod **prefers** or **avoids** certain nodes.  

🔴 `postFilter` (Extension Point)  
📌 **What it does?** → If no nodes were selected, this step tries to **retry scheduling**.  

🔹 Example:  
Imagine a Pod needs 4GB RAM, but a node has only 2GB RAM. The `filter` stage will **remove** that node from the list.  

---

# **📌 3. Scoring (Choosing the Best Node)**
### 🔴 `preScore` (Extension Point)  
📌 **What it does?** → Runs before scoring to **prepare** node ranking.  

🔵 **Plugin: TaintToleration**  
✔️ Ensures Pods don’t get blocked by node taints.  

🔴 `score` (Extension Point)  
📌 **What it does?** → Assigns a **score** to each remaining node.  

🔵 **Plugins:**  
✔️ `NodeResourcesFit` → Prefers nodes with enough resources.  
✔️ `ImageLocality` → Prefers nodes that **already have the Pod’s image** cached (faster startup 🚀).  
✔️ `NodeAffinity` → Prefers nodes that match the Pod’s affinity rules.  

🔴 `reserve` (Extension Point)  
📌 **What it does?** → Temporarily reserves a node **before binding**.  

🔴 `permit` (Extension Point)  
📌 **What it does?** → Some external approvals (like security checks) can **permit or reject** scheduling.  

🔹 Example:  
If a node has **better CPU and memory**, it gets a **higher score** and is more likely to be selected.  

---

# **📌 4. Binding (Assigning the Pod to a Node)**
### 🔴 `preBind` (Extension Point)  
📌 **What it does?** → Runs just before binding the Pod to a node.  

🔴 `bind` (Extension Point)  
📌 **What it does?** → **Assigns the Pod** to the selected node.  

🔵 **Plugin: DefaultBinder**  
✔️ This is the **final step** where the Pod is **officially scheduled** to a node.  

🔴 `postBind` (Extension Point)  
📌 **What it does?** → Runs **after** binding in case any extra work is needed.  

🔹 Example:  
Once a node is selected, this stage **actually places** the Pod on that node.  

---

# **📌 How to Create a Custom Scheduler Profile?**
Now that you understand the **framework**, let’s create a **custom scheduler profile**!  

### **📄 Create a kube-scheduler config file:**
```yaml
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: my-custom-scheduler
    plugins:
      queueSort:
        enabled:
          - name: PrioritySort
      filter:
        enabled:
          - name: NodeResourcesFit
          - name: NodeAffinity
      score:
        enabled:
          - name: NodeResourcesFit
          - name: ImageLocality
      bind:
        enabled:
          - name: DefaultBinder
```

### **🚀 Apply the configuration:**
```sh
kubectl apply -f kube-scheduler-config.yaml
```

### **📌 Assign a Pod to the Custom Scheduler**
Now, tell a Pod to use our custom scheduler:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  schedulerName: my-custom-scheduler
  containers:
    - name: nginx-container
      image: nginx
```

### **🚀 Deploy the Pod**
```sh
kubectl apply -f my-pod.yaml
```

---

# **🎯 Key Takeaways**
✅ **Scheduler Profiles** allow you to customize how Pods are assigned to Nodes.  
✅ **Extension Points** are different **stages** of scheduling.  
✅ **Plugins** are functions that control how scheduling decisions are made.  
✅ **Custom Scheduler Profiles** let you optimize scheduling based on your needs.  

Would you like me to help **deploy a multi-scheduler environment** for testing? 🚀
