### ISSUE TITLE
Configuration map

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#45]
### **ConfigMap in Kubernetes – Asaan Hindi Explanation**  

Bhai, Kubernetes **ConfigMap** ka basic concept ye hai ki agar tu **application me configuration settings (jaise ki database URL, API keys, ya environment variables)** use kar raha hai, to wo directly **code me likhne ki jagah alag store ho sake**.  

Ab maan le tu ek **restaurant ka order management system** bana raha hai. Ye system ek **database** se connected hai, aur database ka **URL, username, password** application ko chahiye hota hai.  

Agar tu ye **configuration values hardcode kar dega** (matlab seedha code me likh dega), to problem ye hogi ki:  
❌ **Agar database ka URL change ho jaye, to code modify karna padega.**  
❌ **Security risk ho sakta hai, agar sensitive information expose ho jaye.**  
❌ **Multiple environments (Dev, Testing, Production) ke liye alag-alag settings handle karna mushkil ho jayega.**  

**Is problem ka solution hai – ConfigMap!**  

---

## **ConfigMap Ka Kaam Kya Hai?**  
ConfigMap ka kaam hai **configuration ko application se alag rakhna** taaki bina code modify kiye **configuration update** ho sake.  

Agar tu **ConfigMap** ka use karega, to application ka code change nahi hoga, bas **ConfigMap update karna padega** aur naye configurations automatically apply ho jayenge! 😎🔥  

---

### **Method 1: ConfigMap YAML File Se**
Ek simple ConfigMap jo **database URL aur log level** store karega:  

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  DATABASE_URL: "mysql://mydb-service:3306"
  LOG_LEVEL: "debug"
```
🔹 **Yeh ConfigMap "my-config" naam se create ho jayega.**  
🔹 **DATABASE_URL aur LOG_LEVEL do key-value pairs hain jo application use karegi.**  

**Is ConfigMap ko Kubernetes me create karne ke liye command chalani padegi:**  
```sh
kubectl apply -f my-config.yaml
```

---

### **Method 2: Command Line Se ConfigMap Banana**
Agar tujhe YAML nahi likhna, to tu **direct command** se ConfigMap bana sakta hai:  
```sh
kubectl create configmap my-config --from-literal=DATABASE_URL=mysql://mydb-service:3306 --from-literal=LOG_LEVEL=debug
```
Yeh **ConfigMap bina YAML likhe hi create ho jayega.**

---

## **ConfigMap Ko Use Kaise Kare?**  
Ab jo ConfigMap bana hai, usko **Pod ke andar inject karna hoga.**  
Iske **3 tareeke hain:**  

### **1️⃣ Environment Variable ke roop me Use Karna**
Agar tu ConfigMap ka data **Pod ke andar environment variable** ke roop me use karna chahta hai, to is tarike se karega:  

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-app-image
    envFrom:
    - configMapRef:
        name: my-config  # ConfigMap ka naam
```
🛠 **Is tarike me** my-config ke **sabhi key-value pairs** as environment variables set ho jayenge.  

---

### **2️⃣ Sirf Ek Particular Key Ko Use Karna**
Agar tu sirf **ek specific value** environment variable ke roop me use karna chahta hai, to ye method use kar:  

```yaml
    env:
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: DATABASE_URL
```
🛠 **Sirf DATABASE_URL environment variable ke roop me set hoga.**  

---

### **3️⃣ File (Volume) Ke Roop Me Use Karna**
Agar tujhe **ConfigMap ko ek file ke roop me use karna hai**, to ise **volume mount** karke Pod me attach karega.  

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-app-image
    volumeMounts:
    - name: config-volume
      mountPath: "/etc/config"
  volumes:
  - name: config-volume
    configMap:
      name: my-config
```
🛠 **Is tarike me ConfigMap ka data `/etc/config/` folder ke andar milega.**  

---

## **ConfigMap Ke Important Commands**
Agar tu ConfigMap ke saath kaam kar raha hai, to ye commands yad rakhna:  

🔹 **ConfigMap List Dekhne Ke Liye:**  
```sh
kubectl get configmap
```

🔹 **Ek Specific ConfigMap Dekhne Ke Liye:**  
```sh
kubectl get configmap my-config -o yaml
```

🔹 **ConfigMap Ko Update Karne Ke Liye:**  
```sh
kubectl apply -f my-config.yaml
```

🔹 **ConfigMap Delete Karne Ke Liye:**  
```sh
kubectl delete configmap my-config
```

---

## **ConfigMap vs Secret – Kya Difference Hai?**
| Feature       | ConfigMap | Secret |
|--------------|-----------|--------|
| **Data Type** | Non-sensitive config (e.g., URLs, log levels) | Sensitive data (e.g., passwords, API keys) |
| **Encoding**  | Plain text | Base64 encoded |
| **Security**  | No encryption | More secure, needs RBAC for access |
| **Usage**     | Environment variables, volumes | Same as ConfigMap, but for secrets |

👉 **ConfigMap ko sensitive data store karne ke liye mat use kar!** Uske liye **Secret** ka use kar.  

---

## **🎯 Interview Me Kaise Answer Kare?**
Agar interviewer puche **"ConfigMap kya hai?"**, to simple answer de:  

> "ConfigMap ek Kubernetes object hai jo key-value pairs me **configuration data store karta hai**. Iska use **application configuration ko code se separate rakhne ke liye hota hai**, taaki bina code modify kiye configuration change ho sake. Ye **environment variables ya volume mount** ke roop me use hota hai."  

Agar puche **"ConfigMap kaise use hota hai?"**, to example de:  
> "Pod ke andar ConfigMap ko environment variable ke roop me ya volume mount karke use kiya jata hai. Example ke taur pe agar kisi application ko `DATABASE_URL` chahiye, to hum ConfigMap me define kar sakte hain aur use directly Pod ke andar environment variable ke roop me inject kar sakte hain."  

---

## **🔥 Final Summary**
✅ **ConfigMap ek key-value pair store hai jo non-sensitive configuration store karta hai.**  
✅ **Application aur configuration ko separate rakhne ke liye use hota hai.**  
✅ **Pod me environment variables ya volume mount ke roop me inject kiya jata hai.**  
✅ **Sensitive data ke liye ConfigMap nahi, balki Secret use karna chahiye.**  

---

Bhai, ab to puri clarity mil gayi hogi! 😎🔥  
Agar koi aur doubt ho ya kuch aur samajhna ho, to bata! 🚀
