### ISSUE TITLE
Kubernetes Secrets & Encryption at Rest

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#47]
#### **1️⃣ What are Kubernetes Secrets?**  
- **Secrets** store sensitive data like passwords, API keys, and certificates.  
- They are stored in **etcd** as **base64-encoded** values, NOT encrypted by default.  
- Base64 is **not encryption**, just an encoding method to hide raw data.  

---

#### **2️⃣ How to Retrieve Secrets?**  
- To check stored Secrets:  
  ```bash
  kubectl get secret my-secret -o yaml
  ```
  **Example Output:**  
  ```yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: my-secret
    namespace: default
  data:
    key1: c3VwZXJzZWNyZXQ=
  type: Opaque
  ```
  - The value of `key1` is **base64-encoded**.

---

#### **3️⃣ Decoding a Secret**  
To reveal the actual secret value, decode it:  
```bash
echo "c3VwZXJzZWNyZXQ=" | base64 --decode
```
**Output:**  
```
supersecret
```

---

#### **4️⃣ Why is This Not Secure?**  
- Base64 encoding is easily reversible.  
- If someone gains access to **etcd**, they can decode secrets.  
- To improve security, **Encryption at Rest** must be enabled.

---

### **🔹 Enabling Encryption at Rest**  
Encryption ensures that Secrets are stored **securely** in etcd.  

#### **🔸 Steps to Enable Encryption at Rest:**
1️⃣ **Create Encryption Config File:**  
   ```yaml
   apiVersion: apiserver.config.k8s.io/v1
   kind: EncryptionConfiguration
   resources:
     - resources:
         - secrets
       providers:
         - aescbc:
             keys:
               - name: key1
                 secret: c29tZXNlY3JldGtleQ==
         - identity: {}
   ```
2️⃣ **Update API Server Config:**  
   Edit `/etc/kubernetes/manifests/kube-apiserver.yaml` and add:  
   ```yaml
   --encryption-provider-config=/etc/kubernetes/encryption-config.yaml
   ```

3️⃣ **Restart API Server:**  
   ```bash
   sudo systemctl restart kubelet
   ```

4️⃣ **Verify Encryption:**  
   Retrieve a secret directly from etcd:  
   ```bash
   ETCDCTL_API=3 etcdctl \
     --endpoints=https://127.0.0.1:2379 \
     --cacert=/etc/kubernetes/pki/etcd/ca.crt \
     --cert=/etc/kubernetes/pki/etcd/peer.crt \
     --key=/etc/kubernetes/pki/etcd/peer.key \
     get /registry/secrets/default/my-secret
   ```
   - If encryption is **enabled**, the output should be **garbled/encrypted**.

---

### **🔹 Best Practices for Secrets Security**  
✅ **Use Encryption at Rest** to protect stored Secrets.  
✅ **Restrict Access to etcd** using RBAC and TLS authentication.  
✅ **Avoid Storing Secrets in Git**—use tools like **Helm Secrets** or **Sealed Secrets**.  
✅ **Use External Secret Managers** like **HashiCorp Vault** for enterprise security.  

---

### **🔹 Alternative Secret Management Solutions**  
🔑 **HashiCorp Vault** → Dynamic secrets with access control.  
📜 **Helm Secrets** → Encrypt secrets before storing them in manifests.  
🔒 **Sealed Secrets (Bitnami)** → Store encrypted secrets safely in Git.  

---

### **🔹 Summary**  
🚀 Kubernetes Secrets are **not encrypted by default**—they are just **base64-encoded**.  
🔐 To **protect secrets**, enable **Encryption at Rest** and follow security best practices.  
🔑 Use external **Secret Managers** for better security in production environments.  

Let me know if you need any clarifications! 🚀
