### ISSUE TITLE
Kubernetes (K8s) - The Complete Guide - (Multi-Container Pod Design Patterns)

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#49]
# Kubernetes (K8s) - The Complete Guide

Kubernetes (K8s) is an **open-source container orchestration** platform that automates the **deployment, scaling, and management** of containerized applications. It helps run applications reliably across different environments, whether on-premises or in the cloud.  

---

# **🌟 Why Use Kubernetes?**
✅ **Scalability** → Easily scale applications up or down based on demand.  
✅ **High Availability** → Ensures applications stay up even if some nodes fail.  
✅ **Automation** → Automates deployment, monitoring, and scaling.  
✅ **Self-Healing** → Restarts failed containers automatically.  
✅ **Rolling Updates & Rollbacks** → Deploy new versions with zero downtime.  
✅ **Resource Efficiency** → Optimizes CPU and memory utilization.  

---

# **📌 Core Components of Kubernetes**
## **🟢 1. Kubernetes Architecture 🏗️**
Kubernetes follows a **master-worker** architecture.  

### **🔹 Control Plane (Master Node)**
Responsible for managing the cluster and scheduling workloads. It includes:  
- **API Server** (kube-apiserver) → Handles all Kubernetes API requests.  
- **Controller Manager** (kube-controller-manager) → Ensures the desired state of the cluster.  
- **Scheduler** (kube-scheduler) → Assigns pods to nodes based on resource availability.  
- **ETCD** → A distributed key-value store for cluster data.  

### **🔹 Worker Nodes**
These nodes run applications inside **Pods** and include:  
- **Kubelet** → Communicates with the API server to manage containers.  
- **Container Runtime** → Runs containers (Docker, containerd, etc.).  
- **Kube Proxy** → Manages network communication between services.  

✅ **Check cluster components:**  
```bash
kubectl get componentstatuses
```

---

## **🟠 2. Kubernetes Objects 🏗️**
Kubernetes **objects** represent the desired state of your cluster.  

### **📦 Pods (Smallest deployable unit)**
- A **Pod** contains one or more containers that share storage and networking.  
- Pods are ephemeral; if they crash, Kubernetes replaces them.  

✅ **Create a Pod:**  
```bash
kubectl run my-pod --image=nginx --restart=Never
```

✅ **List all Pods:**  
```bash
kubectl get pods
```

---

### **📌 Namespaces (Isolation)**
- Namespaces help separate resources in large clusters.  
- Default namespaces: `default`, `kube-system`, `kube-public`.  

✅ **Create a Namespace:**  
```bash
kubectl create namespace my-namespace
```

✅ **List all Namespaces:**  
```bash
kubectl get namespaces
```

---

### **📢 Deployments (Manages Pods & Scaling)**
- **Deployments** ensure the desired number of Pod replicas are running.  
- It allows **rolling updates** and **rollbacks**.  

✅ **Create a Deployment:**  
```bash
kubectl create deployment web --image=nginx
```

✅ **Scale Deployment to 3 replicas:**  
```bash
kubectl scale deployment web --replicas=3
```

✅ **Roll back a Deployment:**  
```bash
kubectl rollout undo deployment web
```

---

### **🔄 Services (Networking)**
- **Services** expose applications running in Pods.  
- They provide stable networking between microservices.  

✅ **Types of Services:**  
1️⃣ **ClusterIP (default)** → Internal communication.  
2️⃣ **NodePort** → Exposes service on a port of each node.  
3️⃣ **LoadBalancer** → Integrates with cloud load balancers.  

✅ **Expose a Deployment using NodePort:**  
```bash
kubectl expose deployment web --type=NodePort --port=80
```

✅ **Get Service details:**  
```bash
kubectl get services
```

---

### **🔒 ConfigMaps & Secrets (Configuration Management)**
- **ConfigMaps** store non-sensitive configuration data.  
- **Secrets** store sensitive data securely (base64 encoded).  

✅ **Create a ConfigMap:**  
```bash
kubectl create configmap my-config --from-literal=ENV=production
```

✅ **Create a Secret:**  
```bash
kubectl create secret generic my-secret --from-literal=password=SuperSecret123
```

✅ **View Secret (base64 encoded):**  
```bash
kubectl get secret my-secret -o yaml
```

---

### **💾 Persistent Volumes (Storage)**
- Kubernetes **Volumes** provide persistent storage to Pods.  
- **Persistent Volume Claims (PVCs)** request storage from Persistent Volumes (PVs).  

✅ **Create a Persistent Volume Claim:**  
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

✅ **Apply the PVC:**  
```bash
kubectl apply -f pvc.yaml
```

✅ **List Persistent Volumes:**  
```bash
kubectl get pv
```

---

### **1️⃣ Sidecar Pattern 🛠️**
A **helper container** runs alongside the main container.  

✅ **Example:** A logging sidecar collecting logs from an application.  
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-example
spec:
  containers:
    - name: main-app
      image: nginx
    - name: logging-sidecar
      image: busybox
      command: ["sh", "-c", "while true; do cat /var/log/app.log; sleep 10; done"]
```

---

### **2️⃣ Adapter Pattern 🔄**
- Converts **output formats** between microservices.  
- **Example:** Transforming logs from JSON to XML before sending them.  

✅ **Example Adapter Pod:**  
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: adapter-example
spec:
  containers:
    - name: main-app
      image: nginx
    - name: adapter
      image: busybox
      command: ["sh", "-c", "cat /logs/json | jq . > /logs/xml"]
```

---

### **3️⃣ Ambassador Pattern 🌍**
- A proxy container **handles external communication**.  
- **Example:** A Redis ambassador acting as a proxy for backend microservices.  

✅ **Example Ambassador Pod:**  
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ambassador-example
spec:
  containers:
    - name: main-app
      image: nginx
    - name: ambassador
      image: redis
      command: ["redis-server", "--slaveof", "redis-master", "6379"]
```

---

# **🔥 Example: Full Kubernetes Deployment**
✅ **Step 1: Create a Deployment**  
```bash
kubectl create deployment web --image=nginx
```

✅ **Step 2: Expose the Deployment**  
```bash
kubectl expose deployment web --type=NodePort --port=80
```

✅ **Step 3: Get the Service Details**  
```bash
kubectl get svc web
```

✅ **Step 4: Access the Application**  
Find the **NodePort** assigned to the service:  
```bash
kubectl get svc web
```
Then, access it using:  
```bash
curl http://<Node-IP>:<NodePort>
```

---

# **🎯 Summary**
✅ **Pods** → Smallest deployable unit 🚀  
✅ **Nodes** → Machines running workloads 🖥️  
✅ **Deployments** → Manages Pods & scaling 🔄  
✅ **Services** → Expose apps inside/outside the cluster 🌐  
✅ **ConfigMaps & Secrets** → Store configuration & sensitive data 🔐  
✅ **Volumes** → Persist data beyond Pod lifecycle 💾  
✅ **Patterns (Sidecar, Adapter, Ambassador)** → Enhance multi-container Pods 🔄  

---

## **📌 Want to Learn More?**
- 🏆 [[Kubernetes Official Docs](https://kubernetes.io/docs/)](https://kubernetes.io/docs/)
- 📖 [[CKA Certification Guide](https://www.cncf.io/certification/cka/)](https://www.cncf.io/certification/cka/)
- 💡 [[CKAD Exam Details](https://www.cncf.io/certification/ckad/)](https://www.cncf.io/certification/ckad/)

🔥 **Ready to deploy your first Kubernetes cluster?** 🚀 Let me know if you need any help! 😊
