### ISSUE TITLE
InPlace Resize of Pod Resources

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#55]
---
InPlace Resize of Pod Resources 
---

### 1. **Definition**  
Kubernetes me **InPlace Resize** ka matlab hai ki bina pod ko restart kiye hi hum uske CPU ya memory resources ko change kar sakte hain. Yeh feature specially **resource optimization** aur **zero downtime scaling** ke liye use hota hai.  

Jab hum ek pod ka CPU ya memory limit badhate hain, to wo **turant reflect** ho jata hai. Agar hum memory limit kam karte hain aur current usage se kam set karte hain, to wo **pending state** me chala jata hai jab tak usage us limit ke andar na aa jaye.  

---

### 2. **Example**  
Maan lo ki ek **nginx pod** chal raha hai jisme initial resource allocation kuch is tarah hai:  

```yaml
spec:
  containers:
    - name: nginx
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
```
Agar hum is pod ki memory limit **512Mi** se **1Gi** karna chahein, to hum bina pod restart kiye hi **kubectl edit** ya apply command se **resource limits update** kar sakte hain.  

```yaml
spec:
  containers:
    - name: nginx
      resources:
        limits:
          memory: "1Gi"
```

Yeh update **InProgress** status me rahega jab tak resource allocation complete na ho jaye.  

---

### 3. **What to Take Care?**  
- **QoS Class nahi change hoti**: Agar ek pod `Guaranteed` class ka hai to `BestEffort` ya `Burstable` me convert nahi ho sakta.  
- **Init aur Ephemeral Containers resize nahi hote**: Sirf main containers ke resources update ho sakte hain.  
- **Limits ko remove nahi kar sakte**: Ek baar resource limit set hone ke baad use **0** ya null nahi kiya ja sakta.  
- **Memory Limit Reduction Care**: Agar ek container already `600Mi` memory use kar raha hai aur hum limit `512Mi` set kar dete hain, to resize **pending state** me rahega jab tak usage kam na ho jaye.  
- **Windows Pods Supported nahi hai**: Windows-based Kubernetes pods ka InPlace resize nahi ho sakta.  

---

### 4. **How to Enable this Feature?**  
Yeh feature **Kubernetes v1.27+** versions me **default enabled** hota hai. Lekin agar older version use kar rahe hain, to `feature gate` enable karna padega.  

Agar manually enable karna ho to kube-apiserver me yeh flag add karein:  
```sh
--feature-gates=InPlacePodVerticalScaling=true
```

---

### 5. **How to Update Resize Policy?**  
Agar kisi pod ko dynamically resize karna hai, to uski **resize policy** ko bhi specify karna hota hai.  

```yaml
spec:
  containers:
    - name: nginx
      resizePolicy:
        - resourceName: "cpu"
          policy: "RestartNotRequired"
        - resourceName: "memory"
          policy: "RestartNotRequired"
```
Yahan `"RestartNotRequired"` ka matlab hai ki pod **bina restart kiye** resize ho sakta hai. 

Agar `"RestartRequired"` set kiya ho, to resize hone ke liye **pod ko restart** karna padega.

---

### 6. **Limitations**  
- **CPU aur memory ke alawa koi aur resource change nahi hota**  
- **QoS class change nahi hoti**  
- **Init aur ephemeral containers ka resize nahi hota**  
- **Once set, resource requests aur limits remove nahi ho sakte**  
- **Agar memory ka resize usage se kam set kiya to InProgress rahega**  
- **Windows Pods ka resize nahi hota**  

---

### **Conclusion**  
Agar Kubernetes cluster me real-time scaling aur performance optimization chahiye to **InPlace Resize** kaafi useful hai. Isse downtime kam hota hai aur **pods ko bina restart kiye** resources adjust ho sakte hain.  

Agar tum apne Kubernetes environment me yeh feature enable kar rahe ho, to ensure karo ki:
- Kubernetes version 1.27+ ho  
- Resize policies properly define ho  
- QoS aur memory usage restrictions dhyan me rakhi jaye
