### ISSUE TITLE
Backup and Restore Methods in Kubernetes

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#61]
# **Backup and Restore Methods in Kubernetes**

## **1. Resources Configuration Approaches**

Kubernetes me resources ko configure karne ke do tareeke hote hain:

### **a. Imperative Approach**
- Isme **directly kubectl commands** ka use karke resources create ya modify kiye jate hain.
- Ye **quick fixes** ke liye useful hota hai, but **scalability aur consistency** ke liye sahi nahi hota.

#### **Commands:**
```sh
kubectl create deployment myapp --image=nginx
kubectl scale deployment myapp --replicas=3
kubectl delete pod myapp-pod
```
- **Pros:** Simple and fast for quick changes.
- **Cons:** Changes track nahi hote, reproducibility nahi hoti.

---

### **b. Declarative Approach**
- Is approach me **YAML files** ka use hota hai, jisme hum **infrastructure as code** likhte hain.
- Changes **trackable hote hain (GitOps)** aur **automate** kiye ja sakte hain.

#### **Example YAML:**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
```
#### **Commands to Apply:**
```sh
kubectl apply -f myapp-deployment.yaml
kubectl delete -f myapp-deployment.yaml
```
- **Pros:** Trackable, reproducible, and version-controlled.
- **Cons:** Pehle se planning aur YAML writing ki zaroorat hoti hai.

---

### **a. ETCD Cluster**
- **ETCD Kubernetes ka brain hota hai.** Isme **cluster state, configurations, secrets, aur network policies** stored hote hain.
- **Distributed key-value store** hota hai jo **high availability** ensure karta hai.
- ETCD me jo bhi data store hota hai, uska backup lena critical hota hai, taki agar kuch galat ho to restore kiya ja sake.

#### **Check ETCD Status:**
```sh
kubectl get pods -n kube-system | grep etcd
```

#### **Check Cluster Members:**
```sh
ETCDCTL_API=3 etcdctl member list --endpoints=https://127.0.0.1:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key
```

---

### **b. Persistent Volume (PV) & Persistent Volume Claims (PVC)**
- Kubernetes me **data loss avoid** karne ke liye **Persistent Volumes** use hote hain.
- **PV ek cluster-wide storage resource hota hai, jo different pods ke beech share ho sakta hai.**
- **PVC** ek request hota hai jo pods storage ke liye karte hain.

#### **Example PV Configuration:**
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
```

#### **Example PVC Configuration:**
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
```

---

### **Backup ETCD Data:**
```sh
ETCDCTL_API=3 etcdctl snapshot save /backup/etcd-snapshot.db \
  --endpoints=https://127.0.0.1:2379 \
  --cacert=/etc/kubernetes/pki/etcd/ca.crt \
  --cert=/etc/kubernetes/pki/etcd/server.crt \
  --key=/etc/kubernetes/pki/etcd/server.key
```

### **Restore ETCD Data:**
```sh
ETCDCTL_API=3 etcdctl snapshot restore /backup/etcd-snapshot.db \
  --data-dir /var/lib/etcd-new
```
```sh
mv /var/lib/etcd /var/lib/etcd-old
mv /var/lib/etcd-new /var/lib/etcd
systemctl restart kube-apiserver
```

---

### **a. Exporting All Kubernetes Resources**
```sh
kubectl get all --all-namespaces -o yaml > cluster-backup.yaml
```

### **b. Restoring Resources**
```sh
kubectl apply -f cluster-backup.yaml
```

---

## **5. Disaster Recovery Strategies in Kubernetes**
- **Cluster Auto-healing:** Node failure hone pe automatic pod rescheduling enable karein.
- **Multi-region Backup:** Backups ko multiple cloud locations me store karein.
- **Service Mesh Integration:** Istio ya Linkerd jaise service mesh ka use karein for fault tolerance.
- **Application-Level Replication:** Stateful applications ke liye database replication enable karein.

---

### **a. Storing Configurations in GitHub (GitOps Approach)**
```sh
git init
git add cluster-backup.yaml
git commit -m "Kubernetes backup"
git push origin main
```

### **b. Automating Backups using GitHub Actions**
```yaml
name: Kubernetes Backup
on:
  schedule:
    - cron: '0 0 * * *' # Daily backup at midnight
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Backup Kubernetes Resources
        run: |
          kubectl get all --all-namespaces -o yaml > cluster-backup.yaml
      - name: Commit and Push Backup
        run: |
          git add cluster-backup.yaml
          git commit -m "Daily Kubernetes Backup"
          git push
```

### **c. Deploying from GitHub to Kubernetes (CI/CD)**
```yaml
name: Deploy to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Apply Kubernetes Configuration
        run: |
          kubectl apply -f deployment.yaml
```

---

## **Conclusion**
- **Backup & restore critical hain** for Kubernetes clusters.
- **Disaster recovery strategies adopt karna zaroori hai.**
- **GitHub ko backup aur CI/CD ke liye use karna best practice hai.** 🚀
