### ISSUE TITLE
Kubernetes Authentication aur Authorization Process

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#63]
---
Kubernetes Authentication aur Authorization Process  (In next - Ticket -- Official way me bhi documented hai) 
---

Bhai! Soch, ek secret mafia gang hai jisme sirf selected bande hi ghus sakte hain. Par yeh decide kaun karega ki kaun andar aa sakta hai aur kaun nahi? 🤔

Yehi kaam Kubernetes mein Authentication aur Authorization ka hota hai! Ekdum high-security zone jisme bina permission ke ghusna matlab apni waat lagwana! 🕵️‍♂️💀

---

### **🛂 Authentication (Tere paas ID hai?)**

**Official Definition:** Authentication ek process hai jisme ek user ya service ki identity verify ki jati hai taaki system confirm kar sake ki jo access maang raha hai, woh authorized hai ya nahi.

Authentication ka matlab hai verify karna ki jo banda system me entry maang raha hai, woh asli hai ya farzi. 🤨

🔹 **Client Certificates** – Jaise ek VIP entry pass 🏅  
🔹 **Bearer Tokens** – Temporary permission, jaise ek din ka guest pass 🎟️  
🔹 **Basic Authentication** – Username-password system (Par bhai yeh purana ho chuka hai, ab secure nahi hai!) 🚫  
🔹 **OIDC, LDAP, Service Accounts** – Ekdum high-tech security systems! 🔐

Ek real-life example le:  
Imagine kar ki tu ek high-profile club ke gate pe hai, bouncer khada hai. Agar tere paas ID nahi hai ya fake hai, toh bouncer tujhe tight slap maar ke wapas bhej dega! 🤕

---

### **🔓 Authorization (Tujhe andar jaake kya karna hai?)**

**Official Definition:** Authorization ek process hai jisme ek authenticated user ko specific resources par access dene ya deny karne ka decision liya jata hai.

Ek baar andar aa gaya toh iska matlab nahi ki tu har jagah ja sakta hai! 👀

🎯 Authorization yeh decide karta hai ki ek user kya kar sakta hai aur kya nahi. Example ke liye:

- Agar tu ek VIP hai toh tujhe private lounge ka access milega. 🥂
- Agar tu normal member hai toh bas dance floor tak limited hai. 🎶
- Agar tu staff hai toh tujhe backstage entry milegi. 🏗️

Kubernetes mein bhi kuch aise hi rules hote hain:  
✅ **Node Authorization** – Nodes ke access ko manage karta hai 🖥️  
✅ **RBAC (Role-Based Access Control)** – Users ko specific roles assign karta hai 🎭  
✅ **ABAC (Attribute-Based Access Control)** – Policy-based access system 📜  
✅ **Webhook Authorization** – Ek external service jo permission decide karti hai 🌐

---

### **⚠️ Basic Authentication Setup (Deprecated in v1.19) ⚠️**

🚨 **WARNING:** Yeh sirf seekhne ke liye hai, production me mat lagana warna teri security leak ho sakti hai! 🚨

#### **Step 1: User Details File Bana**

```bash
mkdir -p /tmp/users
cat <<EOF > /tmp/users/user-details.csv
password123,user1,u0001
password123,user2,u0002
password123,user3,u0003
password123,user4,u0004
password123,user5,u0005
EOF
```

#### **Step 2: kube-apiserver File Edit Kar**

File location: `/etc/kubernetes/manifests/kube-apiserver.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --authorization-mode=Node,RBAC
    - --basic-auth-file=/tmp/users/user-details.csv
    image: k8s.gcr.io/kube-apiserver-amd64:v1.11.3
    name: kube-apiserver
    volumeMounts:
    - mountPath: /tmp/users
      name: usr-details
      readOnly: true
  volumes:
  - hostPath:
      path: /tmp/users
      type: DirectoryOrCreate
    name: usr-details
```

#### **Step 3: RBAC Role and RoleBinding Create Kar**

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```

#### **Step 4: Authentication Test Kar**

```bash
curl -v -k https://localhost:6443/api/v1/pods -u "user1:password123"
```

Agar sab kuch sahi raha toh tujhe pods ki details milengi. Warna error aayega aur tujhe dobara sochna padega ki tu kaha galti kar raha hai! 🤯

---

### **🎯 TL;DR (Ek Nazar Mein)**

✅ **Authentication** - Pehchaan verify hoti hai (VIP entry pass ya ID check) 🛂  
✅ **Authorization** - Access define hota hai (Tujhe kaha tak ghusne diya jayega?) 🚪  
✅ **RBAC** - Roles assign karta hai (Kaun kya kar sakta hai?) 🎭  
✅ **Basic Authentication** - Bhai yeh sirf learning ke liye hai, production me mat laga warna tandoor ban jayega! 🔥

Agar yeh sab samajh aa gaya toh samajh le Kubernetes security ke gate pe tu khud ek bouncer ban gaya! 🏋️‍♂️🔥
