### ISSUE TITLE
Kubernetes Authentication aur Authorization Process

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#64]
---
🔹 Kubernetes Authentication aur Authorization Process 🔹
---
Kubernetes me security ek important aspect hai, jisme Authentication (pramanikaran) aur Authorization (anumati) ki process kaafi crucial role play karti hai. Ye ensure karta hai ki sirf authorized users aur services hi system me entry le sakein aur resources ka access le sakein.

---

### **🛂 Authentication (Pramanikaran)**

**Official Definition:** Authentication ek process hai jisme kisi user ya service ki identity verify ki jati hai taaki ensure ho sake ki voh authorized hai ya nahi.

Authentication ka main purpose ye hai ki system me login karne wala user asli hai ya koi unauthorized entity hai.

✅ **Authentication ke types:**
- **Client Certificates** – Digital certificates ka use karke authentication.
- **Bearer Tokens** – Temporary token-based authentication system.
- **Basic Authentication** – Username aur password ke through (lekin ab ye secure nahi mana jata).
- **OIDC, LDAP, Service Accounts** – Advanced authentication methods.

🔹 **Example:**  
Socho tum ek high-security office me entry lena chahte ho. Gate pe ek security guard hai jo tumse ID proof maang raha hai. Agar tumhare pass sahi credentials nahi hain, toh gate pe hi reject ho jaoge! 🚪❌

---

### **🔓 Authorization (Anumati Process)**

**Official Definition:** Authorization ek process hai jo decide karta hai ki ek authenticated user ko kaunse resources ka access milna chahiye aur voh unke sath kya kar sakta hai.

Authentication hone ke baad, Authorization control karta hai ki user ka access level kya hoga.

✅ **Authorization ke types:**
- **Node Authorization** – Nodes ke liye special access control.
- **RBAC (Role-Based Access Control)** – Users ko specific roles assign karna.
- **ABAC (Attribute-Based Access Control)** – Policies ke basis pe access control.
- **Webhook Authorization** – External services ke through permission management.

🔹 **Example:**  
Library me entry milne ka matlab ye nahi ki tum sari books uthakar ghar le ja sakte ho! Tum sirf pad sakte ho ya borrow kar sakte ho. Kubernetes me bhi authorization decide karta hai ki ek user kya kar sakta hai! 📚🔒

---

### **⚠️ Basic Authentication Setup (v1.19 me Deprecated) ⚠️**

🚨 **Important Note:** Ye sirf learning purposes ke liye hai, isko production (real-world deployment) me use nahi karna chahiye.

#### **Step 1: User Details File Banao**

```bash
mkdir -p /tmp/users
cat <<EOF > /tmp/users/user-details.csv
password123,user1,u0001
password123,user2,u0002
password123,user3,u0003
password123,user4,u0004
password123,user5,u0005
EOF
```

#### **Step 2: kube-apiserver File ko Modify Karo**

File Location: `/etc/kubernetes/manifests/kube-apiserver.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --authorization-mode=Node,RBAC
    - --basic-auth-file=/tmp/users/user-details.csv
    image: k8s.gcr.io/kube-apiserver-amd64:v1.11.3
    name: kube-apiserver
    volumeMounts:
    - mountPath: /tmp/users
      name: usr-details
      readOnly: true
  volumes:
  - hostPath:
      path: /tmp/users
      type: DirectoryOrCreate
    name: usr-details
```

#### **Step 3: RBAC Role aur RoleBinding Banao**

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```

#### **Step 4: Authentication Test Karo**

```bash
curl -v -k https://localhost:6443/api/v1/pods -u "user1:password123"
```

Agar sab kuch sahi hai, toh user ko pods ki list mil jayegi. Nahi toh authentication error aayegi.

---

### **🔹 Quick Recap (TL;DR)**

✅ **Authentication** - User ki identity verify karna.  
✅ **Authorization** - User ko resources ka access dena.  
✅ **RBAC** - Users ko pre-defined roles assign karna.  
✅ **Basic Authentication** - Sirf learning ke liye, production me use na karein! ❌

Ye pura process Kubernetes security ka ek major part hai. Isko sahi tarike se implement karna zaroori hai! 🔥🚀
