### ISSUE TITLE
Custom Resource Definition (CRD) Kya Hai

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#80]
Custom Resource Definition (CRD) ko ache se samjhaunga, Operator Framework bhi add karunga, aur do extra topics bhi daal dunga jo useful honge. Sab kuch step-by-step, Hinglish mein, detail mein likhta hoon. Taiyaar ho jao!

---

### Custom Resource Definition (CRD) Kya Hai?
Kubernetes mein jo default resources hote hain—like Pods, Deployments, Services, ConfigMaps—yeh sab pre-defined hote hain. Lekin kabhi-kabhi aapko apne application ke liye kuch special chahiye hota hai jo inme fit nahi hota. Tab aap use karte ho **Custom Resource Definition (CRD)**. Yeh ek tarika hai jisse aap apna khud ka resource type bana sakte ho, aur Kubernetes ke API ke through usko manage kar sakte ho, bilkul default resources ki tarah.

Simple bolo toh: CRD bolta hai, "Bhai, mujhe ek naya resource type bana do jo meri zarurat ke hisaab se kaam kare, aur Kubernetes isko samajh le."

---

#### 1. **CRD Ki Basic Definition**
- CRD ek YAML file hoti hai jo Kubernetes ko batati hai ki ek naya resource type kaisa hoga—uske fields, structure, aur rules kya honge.
- Yeh banane ke baad, aap iska instance bana sakte ho, jisko **Custom Resource (CR)** kehte hain.
- Example: Agar aapko "Student" naam ka resource chahiye jisme "name", "rollNumber", "class" fields ho, toh CRD banate ho, phir ek instance banate ho jaise "student-ravi".

#### 2. **Kaise Kaam Karta Hai?**
- CRD ko apply karne ke baad, Kubernetes ke API server mein ek naya endpoint ban jata hai.
- Aap isko `kubectl` commands se create, get, update, delete kar sakte ho.
- Lekin CRD khud kuch logic nahi chalati—uske liye aapko ek **Custom Controller** banana padta hai jo is resource ke instances ko monitor kare aur unpe kaam kare.

#### 3. **CRD Ke Components**
- **apiVersion**: Usually `apiextensions.k8s.io/v1`.
- **kind**: `CustomResourceDefinition`.
- **metadata**: Name of the CRD (e.g., `students.example.com`).
- **spec.group**: API group jo aapka custom resource represent karega (e.g., `example.com`).
- **spec.versions**: CRD ke versions (e.g., `v1`), jo schema define karte hain.
- **spec.scope**: `Namespaced` (namespace-specific) ya `Cluster` (cluster-wide).
- **spec.names**: Resource ke names—plural, singular, kind, aur shortNames.

#### 4. **Schema Validation**
- CRD mein `openAPIV3Schema` section hota hai jisme aap define karte ho ki custom resource ka structure kaisa hoga—jaise fields, data types, required fields, etc.
- Example: Agar "Student" resource mein "name" compulsory hai, toh yeh schema mein mention karna padta hai.

#### 5. **CRD vs Controller**
- CRD sirf ek definition hai—jaise ek blueprint ya skeleton.
- Controller ek program hota hai (usually Go language mein) jo CRD ke instances ko padhta hai aur unpe logic apply karta hai—like deployment chalu karna ya status update karna.

---

### Operator Framework Bhi Samjho
CRD ke saath aksar **Operator Framework** ka zikr aata hai, jo ek advanced concept hai. Yeh CRD ko aur powerful banata hai.

#### Operator Kya Hai?
- Operator ek custom controller hota hai jo CRD ke saath milke kaam karta hai. Yeh human operator ka kaam automate karta hai.
- Example: Agar aapka "Database" CRD hai, toh Operator usko manage karega—jaise backup lena, scaling karna, ya failures ko handle karna.

#### Operator Framework Kya Hai?
- Yeh ek toolkit hai (by Red Hat) jo Operators banane mein madad karta hai. Isme tools hote hain jaise:
  - **Operator SDK**: CLI tool to create, build, aur deploy Operators.
  - **Operator Lifecycle Manager (OLM)**: Operators ko cluster mein install aur manage karne ke liye.

#### CRD + Operator Ka Flow
1. CRD banate ho—jaise "Database".
2. Operator banate ho jo "Database" CR ko samajhta hai.
3. Jab aap ek CR apply karte ho (e.g., `my-db`), Operator usko dekhta hai aur logic chalata hai—jaise database pod deploy karna.

---

### Example – Full Detail Mein
Chalo, ek "CronTab" resource banate hain jo scheduled tasks ko manage kare.

#### Step 1: CRD Ki YAML
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                  description: "Cron schedule format"
                image:
                  type: string
                  description: "Container image to run"
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
              required:
                - cronSpec
                - image
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
      - ct
```

#### Step 2: CRD Apply Karo
```bash
kubectl apply -f crontab-crd.yaml
```

#### Step 3: Custom Resource Banayein
```yaml
apiVersion: stable.example.com/v1
kind: CronTab
metadata:
  name: my-cron-job
spec:
  cronSpec: "* * * * */5"
  image: my-cron-image:latest
  replicas: 2
```

#### Step 4: CR Apply Karo
```bash
kubectl apply -f my-cron-job.yaml
```

#### Step 5: Check Karo
```bash
kubectl get crontabs
# Ya
kubectl get ct
```

Output:
```
NAME         AGE
my-cron-job  2m
```

#### Step 6: Operator Ka Role
- CRD ban gaya, lekin yeh khud cron job nahi chalayega.
- Ek Operator banega jo `cronSpec` padhega, `image` se pod banayega, aur `replicas` ke hisaab se scale karega.

---

### Sare Commands – Full List
1. **CRD Create**:
   ```bash
   kubectl apply -f <crd-file>.yaml
   ```

2. **CRD List**:
   ```bash
   kubectl get crd
   ```

3. **CRD Details**:
   ```bash
   kubectl describe crd <crd-name>
   ```

4. **CR Create**:
   ```bash
   kubectl apply -f <cr-file>.yaml
   ```

5. **CR List**:
   ```bash
   kubectl get <plural-name>
   # Example: kubectl get crontabs
   ```

6. **CR Delete**:
   ```bash
   kubectl delete <plural-name>/<cr-name>
   # Example: kubectl delete crontab/my-cron-job
   ```

7. **CRD Delete**:
   ```bash
   kubectl delete crd <crd-name>
   ```

8. **Debugging**:
   ```bash
   kubectl get crd <crd-name> -o yaml
   kubectl get <plural-name>/<cr-name> -o yaml
   ```

9. **Operator Install (via OLM)**:
   ```bash
   kubectl apply -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.22.0/olm.yaml
   ```

---

#### 1. **CRD Versioning**
- CRD mein multiple versions ho sakte hain (e.g., `v1alpha1`, `v1`).
- `spec.versions` mein define karte hain. Ek version `storage: true` hota hai jo data store karta hai.
- Example:
  ```yaml
  versions:
    - name: v1alpha1
      served: true
      storage: false
    - name: v1
      served: true
      storage: true
  ```

#### 2. **Webhooks with CRD**
- Aap CRD ke saath **ValidatingWebhook** aur **MutatingWebhook** laga sakte ho.
- ValidatingWebhook: CR apply hone se pehle check karta hai (e.g., "replicas" 10 se zyada nahi hona chahiye).
- MutatingWebhook: CR ko modify karta hai apply hone se pehle (e.g., default value set karna).

---

### Interview Questions – Taiyaari Ke Liye
1. **CRD Kya Hai Aur Yeh Default Resources Se Alag Kaise Hai?**  
   - CRD custom resources define karta hai jo user-specific hote hain, jabki default resources Kubernetes ke built-in hote hain.

2. **CRD Aur Operator Mein Kya Difference Hai?**  
   - CRD structure deta hai, Operator us structure pe logic chalata hai.

3. **Schema Validation Kaise Kaam Karta Hai?**  
   - `openAPIV3Schema` mein fields, types, aur rules define karte hain.

4. **Operator Framework Kyun Use Karte Hain?**  
   - Complex applications ko automate karne ke liye, jo CRD ke saath milke kaam karta hai.

5. **CRD Ka Scope Kya Hota Hai?**  
   - `Namespaced` ya `Cluster`, `spec.scope` mein define hota hai.

6. **Agar CRD Delete Ho Jaye, CRs Ka Kya Hoga?**  
   - Saare CRs bhi delete ho jate hain, unless finalizers use kiye ho.

7. **Webhooks CRD Ke Saath Kaise Use Hote Hain?**  
   - Validation ya mutation ke liye, API server se integrate hote hain.

---

### Summary
Bhai, ab toh full detail ho gaya! CRD se lekar Operator Framework, commands, examples, extra topics (versioning, webhooks), aur interview questions—sab cover kar diya. Ab tu CRD ka boss ban gaya hai. Koi doubt ho toh bol, clear kar dunga!
