### ISSUE TITLE
Kubernetes Ingress: Foundations se Advanced Tak

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#89]
I will explain har cheez in detail, step-by-step, covering theory, practical aspects, your provided notes, and everything else you asked for (including annotations, rewrite-target, examples, interview prep, and more). Ye explanation itna solid hoga ki beginner se leke pro tak sab samajh jayenge. Let’s go! 

---

### **1. Foundation Level: Ingress Kya Hai?**

**Basic Funda**:  
Ingress ek Kubernetes resource hai jo **external HTTP/HTTPS traffic** ko cluster ke andar ke services tak route karta hai. Socho, tumhare paas ek web application hai, aur users `example.com` ya `example.com/watch` hit karte hain. Ingress decide karta hai ki yeh request kaunse pod ya service pe jayega. Ye ek smart traffic manager ki tarah kaam karta hai.

**Why Ingress?**  
- **Load Balancer ka Upgrade**: Ek LoadBalancer service ek hi app ko expose karta hai aur cloud provider pe ek alag IP deta hai. Ingress ek hi entry point se multiple apps ko handle kar sakta hai based on URL path ya hostname.
- **Path-Based Routing**: `/watch` ko ek service pe, `/wear` ko dusre pe bhej sakta hai.
- **Host-Based Routing**: `api.example.com` aur `app.example.com` ko alag services pe point kar sakta hai.
- **SSL/TLS**: HTTPS ke liye certificates add kar sakta hai.
- **Centralized Control**: Ek hi resource se saara traffic manage hota hai.

**Components Involved**:  
1. **Ingress Resource**: Ek YAML file jisme rules define hote hain, jaise kaunsa path kaunse service pe jayega.
2. **Ingress Controller**: Ek software (jaise NGINX, Traefik) jo Ingress rules ko implement karta hai. Bina iske Ingress resource koi kaam nahi karega.
3. **Services**: Cluster ke andar ke services jo actual apps ko point karte hain (via pods).
4. **DNS**: External world se connect karne ke liye hostname (e.g., `example.com`) ka DNS setup.

**Simple Example**:  
Maan lo tumhare paas do apps hain:  
- `watch-app` jo `watch-service` pe chalta hai.  
- `wear-app` jo `wear-service` pe chalta hai.  

Tum chaahte ho:  
- `example.com/watch` → `watch-service`  
- `example.com/wear` → `wear-service`  

Ingress resource yeh rules define karega.

---

### **2. Intermediate Level: Ingress Kaise Kaam Karta Hai?**

**Architecture Breakdown**:  
1. **User Request**: User browser se `example.com/watch` hit karta hai.
2. **DNS Resolution**: Yeh request DNS ke through ek external IP pe resolve hota hai (usually Ingress Controller ka LoadBalancer IP).
3. **Ingress Controller**: Controller (jaise NGINX) request ko dekhta hai aur Ingress resource ke rules padhta hai.
4. **Routing**: Rules ke hisaab se request correct service (aur indirectly pods) pe forward hoti hai.
5. **Response**: Service response ko wapas Ingress Controller ke through user tak bhejta hai.

**Key Components in Detail**:  

- **Ingress Resource YAML**:  
  Ek typical Ingress resource aisa dikhta hai:

  ```yaml
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: my-ingress
    namespace: default
  spec:
    rules:
    - host: example.com
      http:
        paths:
        - path: /watch
          pathType: Prefix
          backend:
            service:
              name: watch-service
              port:
                number: 80
        - path: /wear
          pathType: Prefix
          backend:
            service:
              name: wear-service
              port:
                number: 80
  ```

  - **apiVersion**: `networking.k8s.io/v1` (K8s 1.19+ ke liye).
  - **kind**: `Ingress`.
  - **metadata**: Name aur namespace define karta hai.
  - **spec.rules**: Hostname aur paths ke rules.
  - **pathType**: `Prefix`, `Exact`, ya `ImplementationSpecific` (ispe aage detail mein baat karenge).
  - **backend**: Kaunsa service aur port pe request jayega.

- **Ingress Controller**:  
  Ye ek pod ya deployment hai jo cluster mein chalta hai. Popular controllers:  
  - **NGINX Ingress**: Most widely used, flexible, aur feature-rich.  
  - **Traefik**: Modern, easy to configure.  
  - **HAProxy**: High-performance load balancing.  
  - **Contour**: Envoy-based, good for advanced use cases.  

  Controller ko cluster mein deploy karna padta hai (via Helm ya YAML). Example: NGINX Ingress ko deploy karne ke liye:

  ```bash
  helm install ingress-nginx ingress-nginx/ingress-nginx
  ```

  Controller ke bina Ingress resource bas ek file hai, koi kaam nahi karega.

- **Path Types**:  
  Kubernetes Ingress mein teen types ke paths hote hain:  
  - **Exact**: Exact match, e.g., `/watch` sirf `/watch` pe kaam karega, `/watch/abc` nahi.  
  - **Prefix**: Path ke start se match, e.g., `/watch` matches `/watch`, `/watch/abc`, etc.  
  - **ImplementationSpecific**: Controller pe depend karta hai, jaise NGINX regex support karta hai.

- **Default Backend**:  
  Agar koi path match nahi karta, to default backend pe request jata hai:

  ```yaml
  spec:
    defaultBackend:
      service:
        name: default-service
        port:
          number: 80
  ```

**How Traffic Flows**:  
1. User → DNS → Ingress Controller’s LoadBalancer IP.  
2. Controller → Ingress Resource rules dekhta hai.  
3. Rules ke hisaab se → Service → Pods.  
4. Response wapas same path se user tak.

---

### **3. Advanced Level: Annotations, Rewrite-Target, and More**

Ab advanced cheezon pe aate hain, jahan Ingress ki real power dikhti hai.

#### **Annotations**

**Annotations kya hain?**  
Annotations Ingress resource mein extra metadata hoti hain jo controller-specific behavior ko control karti hain. Har controller ke apne annotations hote hain. NGINX Ingress ke kuch common annotations:  
- `nginx.ingress.kubernetes.io/rewrite-target`: URL path ko rewrite karta hai.  
- `nginx.ingress.kubernetes.io/ssl-redirect`: HTTP ko HTTPS pe redirect karta hai.  
- `nginx.ingress.kubernetes.io/limit-rate`: Rate limiting set karta hai.  

**Example**:  
Agar tumhe rate limiting chahiye (say, 10 requests/sec), to:

```yaml
metadata:
  annotations:
    nginx.ingress.kubernetes.io/limit-rate: "10"
```

#### **Rewrite-Target Deep Dive**

**Problem**:  
Maan lo tumhara app `/watch` path pe nahi chalta, bas `/` pe chalta hai. Lekin user `example.com/watch` hit karta hai. Default mein, Ingress `/watch` ko as-it-is backend service pe bhejta hai, jo fail ho sakta hai (404 error). 

**Solution**:  
`rewrite-target` annotation use karo. Ye path ko modify karta hai jab request service tak jati hai.

**Your Notes ka Example**:  
- User hits: `example.com/watch` → Chahiye `watch-service` pe `/`.  
- User hits: `example.com/wear` → Chahiye `wear-service` pe `/`.

**YAML**:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-store-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /watch
        pathType: Prefix
        backend:
          service:
            name: watch-service
            port:
              number: 80
      - path: /wear
        pathType: Prefix
        backend:
          service:
            name: wear-service
            port:
              number: 80
```

**Kaise Kaam Karta Hai?**  
- `/watch` path match hota hai → `rewrite-target: /` ke wajah se `/watch` hata diya jata hai.  
- Request `watch-service:80/` pe jati hai.  
- Same for `/wear` → `wear-service:80/`.

**Complex Rewrite Example**:  
Agar path `/something/xyz` hai aur tumhe bas `/xyz` chahiye, to regex use karo:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rewrite
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: rewrite.bar.com
    http:
      paths:
      - path: /something(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: http-svc
            port:
              number: 80
```

**Breakdown**:  
- Path regex: `/something(/|$)(.*)`  
  - `/something` ke baad ya to `/` ya end-of-string (`|$`).  
  - `(.*)` baaki sab capture karta hai (e.g., `xyz` in `/something/xyz`).  
- `rewrite-target: /$2`: Second captured group (`xyz`) ko `/xyz` ke roop mein forward karta hai.  
- Result: `rewrite.bar.com/something/xyz` → `http-svc/xyz`.

#### **TLS/HTTPS Support**

HTTPS ke liye Ingress TLS certificates ko support karta hai. Steps:  
1. **Create a Secret**: TLS certificate aur key ko secret mein store karo.

   ```bash
   kubectl create secret tls example-tls --cert=tls.crt --key=tls.key
   ```

2. **Add TLS to Ingress**:

   ```yaml
   spec:
     tls:
     - hosts:
         - example.com
       secretName: example-tls
     rules:
     - host: example.com
       http:
         paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: my-service
               port:
                 number: 80
   ```

**What Happens?**  
- `example.com` pe HTTPS requests terminate at Ingress Controller.  
- Controller certificate use karta hai aur traffic ko service pe forward karta hai.

#### **IngressClass**

Agar cluster mein multiple Ingress Controllers hain, to `IngressClass` specify karta hai kaunsa controller Ingress resource ko handle karega.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: example.com
    ...
```

Ya phir annotation use karo:

```yaml
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
```

#### **Imperative Creation (K8s 1.20+)**

As per your notes, ab Ingress ko `kubectl` se directly bana sakte ho:

```bash
kubectl create ingress ingress-test --rule="wear.my-online-store.com/wear*=wear-service:80"
```

- **Breakdown**:  
  - `wear.my-online-store.com/wear*`: Host aur path define karta hai.  
  - `wear-service:80`: Backend service aur port.  
  - `*`: Prefix matching ke liye (like `pathType: Prefix`).  

Ye command ek Ingress resource generate karta hai internally.

---

### **4. Changes in Ingress (Older vs. Newer Versions)**

**Old API vs. New API**:  
- **Old**: `extensions/v1beta1` ya `networking.k8s.io/v1beta1`.  
  - Example:

    ```yaml
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: old-ingress
    spec:
      rules:
      - http:
          paths:
          - path: /old
            backend:
              serviceName: old-service
              servicePort: 80
    ```

- **New (K8s 1.19+)**: `networking.k8s.io/v1`.  
  - Example:

    ```yaml
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: new-ingress
    spec:
      rules:
      - http:
          paths:
          - path: /new
            pathType: Prefix
            backend:
              service:
                name: new-service
                port:
                  number: 80
    ```

**Key Differences**:  
1. **PathType Mandatory**: New API mein `pathType` (`Exact`, `Prefix`, ya `ImplementationSpecific`) specify karna zaroori hai.  
2. **Backend Format**:  
   - Old: `serviceName` aur `servicePort`.  
   - New: `backend.service.name` aur `backend.service.port.number`.  
3. **Cleaner Structure**: New API mein rules aur paths ka structure zyada organized hai.  
4. **Deprecation**: `extensions/v1beta1` ab deprecated hai, so naye clusters mein `networking.k8s.io/v1` use karo.

---

### **5. Good Practical Example (Based on Your Notes)**

**Scenario**:  
- `watch-app` displays video streaming at `http://watch-service/`.  
- `wear-app` displays apparel at `http://wear-service/`.  
- User URLs:  
  - `example.com/watch` → `watch-service:/`  
  - `example.com/wear` → `wear-service:/`  

**Problem Without Rewrite**:  
Agar rewrite-target nahi use kiya, to:  
- `example.com/watch` → `watch-service:/watch` (404 error, kyunki app `/watch` nahi samjhta).  
- `example.com/wear` → `wear-service:/wear` (same issue).

**Solution with Ingress**:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-store-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /watch
        pathType: Prefix
        backend:
          service:
            name: watch-service
            port:
              number: 80
      - path: /wear
        pathType: Prefix
        backend:
          service:
            name: wear-service
            port:
              number: 80
```

**What Happens?**  
- User hits `example.com/watch`.  
- Ingress matches `/watch`, applies `rewrite-target: /`.  
- Request goes to `watch-service:80/`.  
- Same for `example.com/wear` → `wear-service:80/`.

**TLS Version** (Bonus):

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secure-online-store
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
      - example.com
    secretName: example-tls
  rules:
  —

---
### **6. Interview Preparation (Foundation to Advanced)**

**Beginner-Level Questions**:  
1. **What is Ingress in Kubernetes?**  
   - Ingress ek resource hai jo external HTTP/HTTPS traffic ko cluster ke services tak route karta hai based on rules like path ya hostname.  
   - Example: `example.com/watch` ko `watch-service` pe bhejna.

2. **Why use Ingress instead of a LoadBalancer?**  
   - LoadBalancer har service ke liye alag IP deta hai, jo costly hai.  
   - Ingress ek hi IP se multiple services ko path-based ya host-based routing ke through manage karta hai.

3. **What is an Ingress Controller?**  
   - Ek pod ya deployment jo Ingress rules ko implement karta hai. Examples: NGINX, Traefik, HAProxy.

**Intermediate-Level Questions**:  
4. **What is the role of annotations in Ingress?**  
   - Annotations controller-specific configs add karti hain, jaise `rewrite-target` path ko modify karta hai ya `limit-rate` requests ko throttle karta hai.

5. **How does pathType work?**  
   - `Exact`: Exact path match (e.g., `/watch` only).  
   - `Prefix`: Path start se match (e.g., `/watch/abc`).  
   - `ImplementationSpecific`: Controller pe depend karta hai (e.g., regex).

6. **How to troubleshoot Ingress issues?**  
   - Check controller pods: `kubectl get pods -n ingress-nginx`.  
   - Logs dekho: `kubectl logs <pod> -n ingress-nginx`.  
   - Verify service/port match: `kubectl describe ingress`.  
   - DNS settings check karo.  
   - Annotations aur `ingressClassName` sahi hain ya nahi.

**Advanced-Level Questions**:  
7. **Explain rewrite-target with an example.**  
   - Maan lo user `example.com/watch` hit karta hai, lekin app `/` pe expect karta hai.  
   - Annotation `nginx.ingress.kubernetes.io/rewrite-target: /` set karo.  
   - Result: `/watch` hata ke request `/` pe jati hai.

   ```yaml
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /
   spec:
     rules:
     - http:
         paths:
         - path: /watch
           pathType: Prefix
           backend:
             service:
               name: watch-service
               port:
                 number: 80
   ```

8. **How to handle multiple Ingress Controllers in one cluster?**  
   - `IngressClass` resource ya `ingressClassName` field use karo.  
   - Example:

     ```yaml
     spec:
       ingressClassName: nginx
     ```

9. **How to secure Ingress with HTTPS?**  
   - TLS secret create karo: `kubectl create secret tls my-tls --cert=tls.crt --key=tls.key`.  
   - Ingress mein `tls` section add karo:

     ```yaml
     spec:
       tls:
       - hosts:
           - example.com
         secretName: my-tls
     ```

10. **Write an Ingress for complex routing.**  
    - Scenario: `api.example.com/v1` → `api-service`, `app.example.com` → `app-service`.

    ```yaml
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: complex-ingress
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    spec:
      rules:
      - host: api.example.com
        http:
          paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 8080
      - host: app.example.com
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 80
    ```

**Practical Tips for Interviews**:  
- **YAML Mastery**: Interview mein YAML likhne ko bol sakte hain. Simple aur complex dono examples practice karo.  
- **Troubleshooting**: Logs, `kubectl describe`, aur DNS issues ke baare mein confidently baat karo.  
- **Real-World Scenarios**: Multiple services, HTTPS, aur rewrite ke examples do.  
- **Controller Knowledge**: NGINX ke annotations ya Traefik ke features thodi detail mein jaano.

---

### **7. Additional Advanced Topics**

1. **Rate Limiting**:  
   NGINX Ingress ke annotations jaise `limit-rate` ya `limit-connections` se traffic control kar sakte ho.

   ```yaml
   annotations:
     nginx.ingress.kubernetes.io/limit-rate: "100"
     nginx.ingress.kubernetes.io/limit-connections: "10"
   ```

2. **Canary Deployments**:  
   NGINX Ingress canary deployments support karta hai:

   ```yaml
   annotations:
     nginx.ingress.kubernetes.io/canary: "true"
     nginx.ingress.kubernetes.io/canary-weight: "10"
   ```

   - 10% traffic canary service pe jata hai, baaki main service pe.

3. **Session Affinity**:  
   Agar user ka session same pod pe rehna chahiye, to:

   ```yaml
   annotations:
     nginx.ingress.kubernetes.io/affinity: "cookie"
     nginx.ingress.kubernetes.io/session-cookie-name: "MYSESSION"
   ```

4. **Custom Errors**:  
   Custom error pages set kar sakte ho:

   ```yaml
   annotations:
     nginx.ingress.kubernetes.io/custom-http-errors: "404,500,503"
   ```

5. **Metrics and Monitoring**:  
   Ingress Controller metrics expose karta hai (e.g., Prometheus ke liye). NGINX Ingress ke liye:

   ```yaml
   annotations:
     prometheus.io/scrape: "true"
     prometheus.io/port: "10254"
   ```

---

### **8. Summary**

- **Foundation**: Ingress HTTP/HTTPS traffic ko services tak route karta hai. Controller ke bina kaam nahi karta.  
- **Intermediate**: Path types, rules, aur services ke saath kaam karta hai. YAML structure aur basic annotations samjho.  
- **Advanced**: Rewrite-target, TLS, IngressClass, canary deployments, aur rate limiting jaise features power deta hai.  
- **Your Notes**: Watch aur wear apps ke liye rewrite-target ka practical use samajh liya.  
- **Interview Prep**: Beginner se advanced questions, YAML examples, aur troubleshooting tips cover kiye.

Agar koi specific part aur detail chahiye ya koi naya angle explore karna hai, bol do, bhai! 😎

**References**:  
- [Kubernetes Ingress Docs](https://kubernetes.io/docs/concepts/services-networking/ingress/)  
- [NGINX Ingress Annotations](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/)  
- [Kubectl Commands](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-ingress-em-)
