### ISSUE TITLE
ETCD

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#92]
# **ETCD: Kubernetes ka Distributed Database - Full Detailed Guide**  

ETCD ek **highly reliable distributed key-value store** hai jo Kubernetes ke liye **single source of truth** ka kaam karta hai. Ye **Kubernetes Control Plane** ka sabse important component hai. Aaj hum isko **deep detail** mein samjhenge, aur **CKA exam perspective** se dekhenge.  

---

### **1.1 ETCD ka Internal Design**  
ETCD **Raft Consensus Algorithm** pe based hai, jo isko **fault-tolerant** banata hai.  

✔ **Nodes & Cluster:**  
- ETCD **odd number of nodes (3,5,7)** pe chalta hai taaki **leader election** smoothly ho sake.  
- Har node ke paas **full copy** of data hota hai (**strong consistency**).  

✔ **Key-Value Storage:**  
- Data **hierarchical structure** mein store hota hai (e.g., `/registry/pods/default/mypod`).  
- Har key ki **revision history** maintain ki jati hai.  

✔ **Watch Mechanism:**  
- Kubernetes API server **ETCD pe watches** lagata hai taaki koi bhi change (e.g., new pod creation) real-time detect ho sake.  

### **1.2 ETCD vs Other Databases**  
| Feature       | ETCD                          | Traditional DB (MySQL, Postgres) |  
|--------------|------------------------------|--------------------------------|  
| **Consistency** | Strong (CP)                  | Depends (CA/CP)               |  
| **Speed**      | Fast (in-memory + disk sync) | Slower (disk-based)           |  
| **Use Case**   | Config/State Management      | Transactional Data            |  

---

### **2.1 ETCDCTL v2 (Old, Deprecated but Useful for Debugging)**  
```sh
# Key-Value Operations  
etcdctl set /message "Hello ETCD"  
etcdctl get /message  

# Directory Operations  
etcdctl mkdir /app/config  
etcdctl ls /app  

# Cluster Health  
etcdctl cluster-health  

# Backup (v2 style)  
etcdctl backup --data-dir /var/lib/etcd --backup-dir /backup/etcd
```

### **2.2 ETCDCTL v3 (Modern, CKA Exam mein Important)**  
```sh
# Set API Version  
export ETCDCTL_API=3  

# Key-Value Operations  
etcdctl put /message "Hello ETCD v3"  
etcdctl get /message  

# Range Queries (Prefix-based)  
etcdctl get /registry/pods/ --prefix  

# Snapshot (Backup)  
etcdctl snapshot save /backup/etcd/snapshot.db  

# Restore Snapshot  
etcdctl snapshot restore /backup/etcd/snapshot.db --data-dir /var/lib/etcd-new  

# Cluster Status  
etcdctl endpoint status --write-out=table  

# Defragmentation (Reduce Disk Usage)  
etcdctl defrag  

# Compact Old Revisions  
etcdctl compact 1000  # Keeps last 1000 revisions
```

### **2.3 Kubernetes Context mein ETCD Access**  
Kubernetes ETCD ko **TLS se secure** karta hai, isliye certificates ke bina access nahi hoga:  
```sh
kubectl exec -it etcd-master -n kube-system -- sh -c "ETCDCTL_API=3 etcdctl \  
--endpoints=https://127.0.0.1:2379 \  
--cacert=/etc/kubernetes/pki/etcd/ca.crt \  
--cert=/etc/kubernetes/pki/etcd/server.crt \  
--key=/etc/kubernetes/pki/etcd/server.key \  
get / --prefix --keys-only"
```

---

### **3.1 Regular Backups (Must for CKA Exam)**  
ETCD backup lena **CKA exam ka common task** hai. Ye **2 methods** se kar sakte ho:  

#### **Method 1: Manual Snapshot**  
```sh
ETCDCTL_API=3 etcdctl snapshot save /backup/etcd-snapshot.db \  
--endpoints=https://127.0.0.1:2379 \  
--cacert=/etc/kubernetes/pki/etcd/ca.crt \  
--cert=/etc/kubernetes/pki/etcd/server.crt \  
--key=/etc/kubernetes/pki/etcd/server.key
```

#### **Method 2: Using CronJob (Auto-Backup)**  
```yaml
apiVersion: batch/v1beta1  
kind: CronJob  
metadata:  
  name: etcd-backup  
spec:  
  schedule: "0 * * * *"  
  jobTemplate:  
    spec:  
      containers:  
      - name: etcd-backup  
        image: k8s.gcr.io/etcd:3.5.0  
        command: ["/bin/sh", "-c"]  
        args:  
          - "ETCDCTL_API=3 etcdctl snapshot save /backup/etcd-snapshot.db \  
            --endpoints=https://127.0.0.1:2379 \  
            --cacert=/etc/kubernetes/pki/etcd/ca.crt \  
            --cert=/etc/kubernetes/pki/etcd/server.crt \  
            --key=/etc/kubernetes/pki/etcd/server.key"  
        volumeMounts:  
          - mountPath: /etc/kubernetes/pki/etcd  
            name: etcd-certs  
          - mountPath: /backup  
            name: backup  
      volumes:  
        - name: etcd-certs  
          hostPath:  
            path: /etc/kubernetes/pki/etcd  
        - name: backup  
          hostPath:  
            path: /backup  
      restartPolicy: OnFailure
```

### **3.2 Disaster Recovery (ETCD Restore)**  
Agar ETCD corrupt ho jaye, toh **snapshot se restore** karna padega:  

#### **Step 1: Stop kube-apiserver**  
```sh
systemctl stop kube-apiserver
```

#### **Step 2: Restore Snapshot**  
```sh
ETCDCTL_API=3 etcdctl snapshot restore /backup/etcd-snapshot.db \  
--data-dir /var/lib/etcd-restored \  
--cacert=/etc/kubernetes/pki/etcd/ca.crt \  
--cert=/etc/kubernetes/pki/etcd/server.crt \  
--key=/etc/kubernetes/pki/etcd/server.key
```

#### **Step 3: Replace Old Data & Restart Services**  
```sh
mv /var/lib/etcd /var/lib/etcd-old  
mv /var/lib/etcd-restored /var/lib/etcd  
systemctl start etcd kube-apiserver
```

---

### **4.1 Common ETCD Issues & Fixes**  

| Issue                          | Symptoms                          | Solution |  
|--------------------------------|----------------------------------|----------|  
| **ETCD High Latency**          | `kubectl` commands slow          | Check disk I/O (`iotop`), defragment (`etcdctl defrag`) |  
| **Disk Space Full**            | "mvcc: database space exceeded" | Compact old revisions (`etcdctl compact`) |  
| **ETCD Not Healthy**           | `kubectl get cs` shows unhealthy | Check logs (`kubectl logs etcd-master -n kube-system`), restart ETCD |  
| **Certificate Errors**         | "x509: certificate signed by unknown authority" | Verify cert paths, regenerate using `kubeadm` |  

### **4.2 ETCD Logs Analysis**  
```sh
kubectl logs etcd-master -n kube-system | grep -i "error\|warning"
```
- **"raft: failed to send message"** → Network issue between ETCD nodes.  
- **"compaction not finished"** → Disk slow, compaction stuck.  
- **"etcdserver: request timed out"** → High load, increase `--heartbeat-interval`.  

---

### **5.1 Performance Optimization**  
✔ **Increase ETCD Quota:**  
```sh
--quota-backend-bytes=8589934592  # 8GB limit
```
✔ **Adjust Election Timeouts:**  
```sh
--heartbeat-interval=100  # Milliseconds  
--election-timeout=1000   # Milliseconds
```
✔ **Use Fast SSD:** ETCD **sequential writes** karta hai, HDD slow hoga.  

### **5.2 Security Hardening**  
✔ **Enable TLS for Peer Communication:**  
```sh
--peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt  
--peer-key-file=/etc/kubernetes/pki/etcd/peer.key
```
✔ **Enable Audit Logging:**  
```sh
--audit-log-path=/var/log/etcd-audit.log
```

---

## **6. Final Summary (CKA Exam ke Liye Key Points)**  
✅ **ETCD Kubernetes ka distributed database hai, Raft consensus use karta hai.**  
✅ **Always run in odd-numbered clusters (3,5 nodes).**  
✅ **Regular snapshots lo (`etcdctl snapshot save`).**  
✅ **Disk full ho toh `compact` + `defrag` karo.**  
✅ **TLS certificates (`ca.crt`, `server.crt`, `server.key`) ka dhyan rakho.**  
✅ **CKA exam mein `etcdctl` commands, backup/restore, aur troubleshooting puche jaate hain.**
