### ISSUE TITLE
Kubernetes API Server (kube-api-server)

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/ankitiitians#93]
Alright, let’s dive into explaining the **Kubernetes API Server**  with a solid example, configurations, and some senior-level questions to make it crystal clear. I’ll keep it detailed yet simple, aur thoda desi swag bhi add karenge! 😎

---

### **Kya hai ye Kubernetes API Server?**
Kubernetes API Server ek tarah ka "control room" hai jo Kubernetes cluster ka dil hai. Ye ek RESTful API provide karta hai jo cluster ke saare components (like Pods, Services, Deployments) ko ek doosre se baat karne deta hai. Isko aap aisa samjho ki ek **waiter** hai jo restaurant (Kubernetes cluster) mein orders (commands) leta hai aur kitchen (other components) tak pahunchata hai.

- **Kaam kya karta hai?**
  - Ye client (like `kubectl`, developers, ya koi external tool) se requests accept karta hai.
  - Ye requests validate karta hai (check karta hai ki request sahi hai ya nahi).
  - Cluster ke state ko **etcd** (ek distributed database) mein store karta hai.
  - Dusre components (like Scheduler, Controller Manager) ke saath coordinate karta hai.

- **Example in real life**:
  Suppose tum ek restaurant ke manager ho. Tum customer (developer) se order (command) lete ho, check karte ho ki order possible hai ya nahi (validation), aur phir chef (worker nodes) ko bolte ho ki dish (application) banao. API Server wahi manager hai jo orders handle karta hai.

---

### **Kaise Kaam Karta Hai?**
1. **Client Request**: Tum `kubectl` se command dete ho, jaise `kubectl create deployment my-app --image=nginx`. Ye command API Server ke paas jaati hai.
2. **Authentication & Authorization**: API Server check karta hai ki tum kaun ho (authn) aur kya tumhe ye kaam karne ka permission hai (authz).
3. **Validation**: Request valid hai ya nahi, ye dekhta hai (e.g., syntax sahi hai, image exists, etc.).
4. **Storage in etcd**: Agar sab theek hai, to ye request ko process karta hai aur cluster ke state ko etcd mein save karta hai.
5. **Communication**: Dusre components (Scheduler, Kubelet) ko batata hai ki kya karna hai.

---

### **Real-World Example with Configurations**
Let’s say tum ek **Nginx web server** deploy karna chahte ho Kubernetes pe. Chalo, step-by-step dekhte hai kaise API Server involve hota hai.

#### **Step 1: Create a Deployment YAML**
Tum ek `nginx-deployment.yaml` file banate ho:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
```

#### **Step 2: Send Request to API Server**
Tum command chalate ho:
```bash
kubectl apply -f nginx-deployment.yaml
```

Ye command **API Server** ke endpoint (`https://<api-server-ip>:6443`) pe ek HTTP POST request bhejta hai. API Server is request ko accept karta hai.

#### **Step 3: API Server ka Kaam**
- **Authentication**: Dekhta hai ki tumhara `kubectl` ka token ya certificate valid hai.
- **Authorization**: Check karta hai ki tumhe Deployment create karne ka permission hai (via RBAC).
- **Validation**: YAML file ke syntax aur fields check karta hai (e.g., `replicas` ka value valid hai ya nahi).
- **Storage**: Deployment object ko etcd mein store karta hai.
- **Action**: Scheduler ko bolta hai ki 3 Pods create karo, aur Kubelet ko bolta hai ki containers start karo.

#### **Step 4: Result**
Tum dekhte ho:
```bash
kubectl get deployments
NAME       READY   UP-TO-DATE   AVAILABLE   AGE
my-nginx   3/3     3            3           10s
```

Ye sab API Server ke wajah se hua!

---

### **API Server ki Configuration**
API Server ko configure karna padta hai taaki wo sahi se kaam kare. Ye configuration `/etc/kubernetes/manifests/kube-apiserver.yaml` mein hoti hai (ya systemd service ke through).

#### **Sample Configuration (Simplified)**
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - name: kube-apiserver
    image: k8s.gcr.io/kube-apiserver:v1.23.0
    command:
    - kube-apiserver
    - --advertise-address=192.168.1.100
    - --etcd-servers=https://127.0.0.1:2379
    - --service-cluster-ip-range=10.96.0.0/12
    - --enable-admission-plugins=NamespaceLifecycle,LimitRanger
    - --authorization-mode=RBAC
    - --secure-port=6443
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
```

#### **Key Flags Explained**
- `--advertise-address`: API Server ka IP jo clients ke liye expose hota hai.
- `--etcd-servers`: etcd ka address jahan cluster state store hota hai.
- `--authorization-mode`: RBAC ya Node authorization mode set karta hai.
- `--enable-admission-plugins`: Extra validation rules enable karta hai (jaise NamespaceLifecycle).
- `--secure-port`: HTTPS port jahan API Server requests sunta hai (default 6443).

---

### **Senior-Level Questions aur Unke Jawab**
Ye questions senior engineers ya architects ke liye hai jo API Server ke deep understanding test karte hai:

#### **Q1: API Server kaise scale karta hai for high availability?**
**Jawab**: 
- API Server ko horizontally scale karne ke liye multiple instances chalaye jaate hai (HA setup mein).
- Har instance ek load balancer (e.g., HAProxy, Nginx) ke peeche hoti hai.
- Sab instances same etcd cluster se connect hote hai taaki state consistent rahe.
- Example: 3 API Server instances chalao, aur ek external load balancer (AWS ELB ya GCP LB) use karo.

#### **Q2: API Server ke performance bottlenecks kya ho sakte hai?**
**Jawab**:
- **etcd latency**: Agar etcd slow hai, API Server ke requests delay honge.
- **High request volume**: Bahut saare clients ek saath requests bhejenge to CPU/memory pressure badhega.
- **Admission controllers**: Complex admission plugins (e.g., webhooks) latency add kar sakte hai.
- **Solution**: etcd ko optimize karo (SSD use karo), API Server ke resources badhao, aur caching (e.g., `--watch-cache-sizes`) enable karo.

#### **Q3: API Server ke security kaise ensure karte hai?**
**Jawab**:
- **TLS encryption**: API Server ke saare communications TLS ke through hote hai.
- **RBAC**: Role-Based Access Control use karo taaki sirf authorized users hi access kare.
- **Admission Control**: Plugins jaise `PodSecurityPolicy` ya `ValidatingWebhook` use karo.
- **Audit Logging**: `--audit-log-path` enable karo taaki saari requests track ho.

#### **Q4: Custom Resources (CRDs) kaise API Server ke saath kaam karte hai?**
**Jawab**:
- CRDs ek tarah ke custom objects hai jo API Server ke REST API ko extend karte hai.
- Tum ek CRD define karte ho (e.g., `MyApp` resource), aur API Server uske liye endpoints bana deta hai (like `/apis/myapp/v1/namespaces/*/myapps`).
- Example: Istio ya Prometheus CRDs banate hai jo API Server ke through manage hote hai.

---

### **API Server Exactly Kya Karta Hai?**
Ek line mein: **API Server Kubernetes cluster ka central hub hai jo saari requests handle karta hai, state manage karta hai, aur components ke beech coordination karta hai.**

- **Kya nahi karta?**
  - Ye scheduling nahi karta (wo Scheduler ka kaam hai).
  - Ye containers directly nahi chalata (wo Kubelet ka kaam hai).

---

### **Extra Tips for Seniors**
- **Monitoring**: API Server ke metrics (like request latency, error rates) ko Prometheus se monitor karo.
- **Rate Limiting**: `--max-requests-inflight` aur `--max-mutating-requests-inflight` flags se API Server ko overload se bachao.
- **Debugging**: `--v=4` flag se verbose logging enable karo agar issues debug karne hai.

---

Agar aur details chahiye ya koi specific topic pe deep dive karna hai (jaise CRDs ya admission controllers), toh bolo! 😄 Aur ye Hinglish explanation kaisa laga?
